"""Generated from the Grim Dawn database - do not edit.

Regenerate after a game patch with:  python devotion.py --regenerate

Which named equipment appears here is chosen in equipmentWanted.py;
components and augments are everything the game has.
"""
from dataModel import Item
from ability import Ability

components = [
	Item('Aether Soul', {"aether %":10, "aether resist":16, "defense":30}, ['amulet', 'medal']),
	Item('Aethersteel Bolts', {"aether":5, "aether %":25, "physical to aether":10}, ['offhand', 'ranged'], Ability('Aether Tendril', {"chance":1, "recharge":2.5, "skillClass":'Skill_AttackSpellChaos', "trigger":'manual', "type":'attack'}, {"duration":{"reduce resist":20, "slow move":40}, "energy":-70, "triggered aether":1187, "weapon damage %":150})),
	Item('Amber', {"electrocute %":25, "lightning":5, "lightning %":25, "physical to lightning":10}, ['axe', 'dagger', 'mace', 'offhand', 'scepter', 'shield', 'sword', 'twohand'], Ability('Empowered Lightning Nova', {"chance":1, "skillClass":'Skill_AttackRadius', "trigger":'manual', "type":'attack'}, {"energy":-55, "triggered lightning":163, "weapon damage %":90})),
	Item('Ancient Armor Plate', {"armor":35, "armor %":8, "armor absorb":8, "physique":18}, ['chest', 'legs']),
	Item('Antivenom Salve', {"acid resist":20, "armor":24, "health/s":10}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item('Arcane Lens', {"defense":40, "elemental":7.5, "elemental %":25, "skill cost %":-6, "spirit %":3}, ['amulet']),
	Item('Arcane Spark', {"energy leech":15, "energy/s %":20, "offense":50, "skill disruption protection":30}, ['amulet', 'medal']),
	Item('Attuned Lodestone', {"crit damage":5, "electrocute %":20, "lightning %":20, "lightning retaliation":130.5, "offense":32}, ['amulet', 'medal'], Ability('Static Charge', {"chance":0.2, "recharge":2, "skillClass":'Skill_AttackRadius', "trigger":'hit', "type":'attack'}, {"stun %":100, "triggered lightning":181, "weapon damage %":15})),
	Item('Ballistic Plating', {"armor":18, "avoid ranged":10, "defense %":2}, ['chest']),
	Item('Battered Shell', {"block %":10, "physique":15}, ['shield'], Ability('Shield Slam', {"chance":1, "recharge":3, "skillClass":'Skill_AttackWeapon', "trigger":'manual', "type":'attack'}, {"energy":-21, "stun %":50, "triggered physical":98.5, "weapon damage %":230})),
	Item('Bindings of Bysmiel', {"defense":25, "energy/s":1, "offense":25}, ['chest'], Ability("Bysmiel's Binding", {"chance":1, "skillClass":'Skill_Passive', "trigger":'passive', "type":'buff'}, {"pet all damage %":20, "pet health %":10})),
	Item('Black Tallow', {"chaos %":10, "chaos resist":16, "defense":30}, ['amulet', 'medal']),
	Item('Bladed Plating', {"health":120, "offense":24, "retaliation %":30}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item('Blazing Ruby', {"fire retaliation":160, "health":160, "health %":4, "retaliation %":16, "slow resist":15}, ['amulet', 'medal']),
	Item('Blessed Steel', {"elemental":5, "elemental %":18, "offense":18, "physical to elemental":10}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword', 'twohand'], Ability('Sacred Strike', {"chance":1, "recharge":3, "skillClass":'Skill_AttackWeapon', "trigger":'manual', "type":'attack'}, {"duration":{"reduce resist":20}, "energy":-32, "triggered elemental":209.5, "weapon damage %":350})),
	Item('Blessed Whetstone', {"bleed %":25, "offense":18, "pierce":5, "pierce %":18}, ['axe', 'ranged', 'sword', 'twohand'], Ability('Behead', {"chance":1, "skillClass":'Skill_AttackWeapon', "trigger":'manual', "type":'attack'}, {"energy":-18, "triggered bleed":[110, 3], "triggered pierce":66, "weapon damage %":120})),
	Item('Bloodied Crystal', {"armor":75, "bleed resist":15, "defense":40}, ['amulet', 'medal', 'ring']),
	Item('Bloody Whetstone', {"bleed":[10, 3], "bleed %":30, "bleed duration":30, "crit damage":5}, ['axe', 'ranged', 'sword', 'twohand'], Ability('Decapitate', {"chance":1, "skillClass":'Skill_AttackWeapon', "trigger":'manual', "type":'attack'}, {"energy":-24, "triggered bleed":[150, 3], "triggered pierce":90, "weapon damage %":145})),
	Item('Bristly Fur', {"constitution %":25, "health":90}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item('Chains of Oleron', {"move speed":6, "offense":30, "offense %":2, "trap resist":24}, ['chest']),
	Item('Chilled Steel', {"cold":3, "cold %":12, "physical to cold":10}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword', 'twohand'], Ability('Ice Spike', {"chance":1, "skillClass":'Skill_AttackProjectile', "trigger":'manual', "type":'attack'}, {"duration":{"slow move":20}, "energy":-18, "triggered cold":77.5, "weapon damage %":22})),
	Item('Chipped Claw', {"physical":4, "physical %":12}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword', 'twohand'], Ability('Slam', {"chance":1, "recharge":2, "skillClass":'Skill_AttackWeaponRadius', "trigger":'manual', "type":'attack'}, {"energy":-20, "triggered physical":50, "weapon damage %":100})),
	Item('Coldstone', {"cold":5, "cold %":25, "frostburn %":25, "physical to cold":10}, ['axe', 'dagger', 'mace', 'offhand', 'scepter', 'shield', 'sword', 'twohand'], Ability('Chilling Weapons', {"chance":1, "skillClass":'Skill_BuffSelfToggled', "trigger":'toggle', "type":'buff'}, {"cold %":75, "duration":{"pet slow move":10, "slow move":10}, "frostburn %":75, "pet cold":8, "pet cold %":75, "pet frostburn %":75, "triggered cold":10})),
	Item('Consecrated Wrappings', {"attack speed":8, "chaos":5.5, "chaos resist":8}, ['arms']),
	Item('Corpse Dust', {"health %":4, "health/s %":24, "vitality resist":10}, ['amulet', 'medal', 'ring']),
	Item('Cracked Lodestone', {"lightning":3, "lightning %":12, "physical to lightning":10}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword', 'twohand'], Ability('Lightning Nova', {"chance":1, "skillClass":'Skill_AttackRadius', "trigger":'manual', "type":'attack'}, {"energy":-25, "triggered lightning":70, "weapon damage %":22})),
	Item('Deathchill Bolts', {"cold":5, "cold %":25, "frostburn %":25, "physical to cold":10, "slow move":25}, ['offhand', 'ranged'], Ability('Greater Ice Spike', {"chance":1, "skillClass":'Skill_AttackProjectile', "trigger":'manual', "type":'attack'}, {"duration":{"slow move":25}, "energy":-32, "triggered cold":201.5, "weapon damage %":50})),
	Item('Dense Fur', {"armor":24, "cold resist":20, "health":90}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item('Devil-Touched Ammo', {"burn %":30, "chaos %":30, "fire":6, "fire %":30, "lifesteal %":6, "physical to fire":10}, ['offhand', 'ranged'], Ability("Demon's Breath", {"chance":0.15, "recharge":3, "skillClass":'Skill_AttackWave', "trigger":'attack', "type":'attack'}, {"lifesteal %":8, "triggered chaos":210.5, "triggered fire":158, "weapon damage %":15})),
	Item('Dread Skull', {"bleed %":30, "bleed duration":30, "pierce %":24, "total speed":5}, ['amulet', 'medal']),
	Item('Ectoplasm', {"energy %":20, "energy/s":3}, ['amulet', 'head', 'medal', 'ring']),
	Item('Eldritch Mirror', {"attack speed":5, "cast speed":5, "vitality resist":10}, ['chest', 'head'], Ability('Eldritch Binding', {"chance":1, "skillClass":'Skill_Passive', "trigger":'passive', "type":'buff'}, {"pet total speed":10})),
	Item('Enchanted Earth', {"armor %":4, "health %":4, "health/s":24}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item('Enchanted Flint', {"burn %":25, "fire":5, "fire %":25, "physical to fire":10}, ['axe', 'dagger', 'mace', 'offhand', 'scepter', 'shield', 'sword', 'twohand'], Ability('Burning Weapons', {"chance":1, "skillClass":'Skill_BuffSelfToggled', "trigger":'toggle', "type":'buff'}, {"burn %":75, "fire %":75, "pet burn":[45, 3], "pet burn %":75, "pet fire":8, "pet fire %":75, "triggered burn":[45, 3], "triggered fire":10})),
	Item('Flintcore Bolts', {"burn":[5, 3], "burn %":25, "fire":5, "fire %":25, "physical to fire":10}, ['offhand', 'ranged'], Ability('Greater Fireblast', {"chance":1, "skillClass":'Skill_AttackProjectile', "trigger":'manual', "type":'attack'}, {"energy":-32, "stun %":50, "triggered burn":[144, 3], "triggered fire":172, "weapon damage %":40})),
	Item('Focusing Prism', {"crit damage":5, "skill cost %":-10, "spirit":18}, ['amulet']),
	Item('Frozen Heart', {"cold resist":10, "freeze resist":21, "health":70, "petrify resist":21}, ['ring']),
	Item('Hallowed Ground', {"defense":25, "defense %":2, "elemental resist":12, "health/s":30}, ['chest']),
	Item('Haunted Steel', {"lifesteal %":8, "physical to vitality":10, "vitality":8, "vitality %":25, "vitality decay %":25}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword', 'twohand'], Ability('Bloodthirster', {"chance":1, "duration":8, "recharge":20, "skillClass":'Skill_BuffSelfDuration', "trigger":'manual', "type":'buff'}, {"bleed %":90, "bleed resist":20, "energy":-58, "lifesteal %":24, "triggered bleed":[122, 3], "vitality decay %":90})),
	Item("Hell's Bane Ammo", {"electrocute %":25, "lightning":5, "lightning %":25, "physical to lightning":10, "stun %":10}, ['offhand', 'ranged'], Ability('Electrifying Weapons', {"chance":1, "skillClass":'Skill_BuffSelfToggled', "trigger":'toggle', "type":'buff'}, {"electrocute %":75, "lightning %":75, "pet electrocute %":75, "pet lightning":8, "pet lightning %":75, "stun %":75, "triggered lightning":10})),
	Item('Hollowed Fang', {"lifesteal %":5, "physical to vitality":10, "vitality %":18, "vitality decay":[6, 3], "vitality decay %":18}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword', 'twohand'], Ability('Blooddrinker', {"chance":1, "duration":8, "recharge":26, "skillClass":'Skill_BuffSelfDuration', "trigger":'manual', "type":'buff'}, {"energy":-50, "lifesteal %":20, "triggered bleed":[54, 3]})),
	Item('Imbued Silver', {"bleed resist":15, "defense":30}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword', 'twohand'], Ability('Void-Ward', {"chance":1, "skillClass":'Skill_BuffSelfToggled', "trigger":'toggle', "type":'buff'}, {"chaos resist":20, "pet chaos resist":20})),
	Item("Kilrian's Shattered Soul", {"attack speed":5, "burn %":40, "fire %":40, "vitality %":40, "vitality decay %":40, "vitality resist":20}, ['chest'], Ability("Kilrian's Flame", {"chance":0.1, "duration":4, "recharge":6, "skillClass":'Skill_BuffAttackRadiusDuration', "trigger":'hit', "type":'buff'}, {"lifesteal %":33, "triggered fire":86, "triggered vitality":122, "triggered vitality decay":[210, 2]})),
	Item('Leathery Hide', {"armor":32, "health %":6, "stun resist":25}, ['head']),
	Item('Living Armor', {"armor absorb":12, "chaos resist":8, "elemental resist":10, "offense":35}, ['chest', 'head', 'shoulders']),
	Item('Mark of Dreeg', {"acid %":30, "light radius":6, "physical to acid":10, "poison":[10, 5], "poison %":30, "reduce resist":15}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword', 'twohand'], Ability("Dreeg's Infinite Gaze", {"chance":0.15, "recharge":2.5, "skillClass":'Skill_AttackProjectileRing', "trigger":'attack', "type":'attack'}, {"duration":{"reduce resist":15}, "triggered acid":55, "triggered poison":[210, 5]})),
	Item('Mark of Illusions', {"defense":32, "elemental %":15, "energy/s":2.5, "spirit":12}, ['amulet', 'ring']),
	Item('Mark of Mogdrogen', {"health %":5, "health/s":15, "health/s %":10, "move speed":10}, ['feet']),
	Item('Mark of the Myrmidon', {"defense":25, "health":120, "physical retaliation":180, "shield recovery":15}, ['shield'], Ability('Blade Barricade', {"chance":1, "duration":3, "recharge":8, "skillClass":'Skill_BuffSelfDuration', "trigger":'manual', "type":'buff'}, {"energy":-52, "physical retaliation":900, "pierce resist":30, "shield recovery":100})),
	Item('Mark of the Traveler', {"health/s":18, "move speed":8, "slow resist":15}, ['feet']),
	Item('Molten Skin', {"armor":24, "fire resist":20}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item('Mutagenic Ichor', {"acid %":10, "physical to acid":10, "poison":[3, 5], "poison %":10}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword', 'twohand'], Ability('Poison Bomb', {"chance":1, "duration":4, "skillClass":'Skill_AttackProjectile', "trigger":'manual', "type":'attack'}, {"energy":-32, "triggered acid":12, "triggered poison":[62, 2], "weapon damage %":12})),
	Item('Mutated Scales', {"health":180, "health %":3}, ['arms', 'chest', 'legs', 'shoulders']),
	Item("Oleron's Blood", {"internal %":40, "offense":24, "physical %":25, "total speed":2}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword', 'twohand'], Ability("Oleron's Might", {"chance":1, "skillClass":'Skill_WPAttack_BasicAttack', "trigger":'manual', "type":'attack'}, {"triggered internal":[190, 5], "triggered physical":122, "weapon damage %":130})),
	Item('Polished Emerald', {"cunning":8, "physique":8, "spirit":8}, ['chest', 'head', 'offhand', 'ring', 'shield']),
	Item('Prismatic Diamond', {"energy absorb":20, "health %":4, "vitality resist":15}, ['head'], Ability('Prismatic Rage', {"chance":1, "duration":8, "recharge":33, "skillClass":'Skill_PassiveOnLifeBuffSelf', "trigger":'low health', "type":'buff'}, {"all damage %":10, "damage absorb":130, "total speed":10})),
	Item('Purified Salt', {"defense":30, "life leech resist":25}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword', 'twohand'], Ability('Aether-Ward', {"chance":1, "skillClass":'Skill_BuffSelfToggled', "trigger":'toggle', "type":'buff'}, {"aether resist":20, "pet aether resist":20})),
	Item('Radiant Gem', {"elemental %":10, "elemental resist":15, "physical to elemental":10}, ['offhand', 'shield'], Ability('Radiant Shield', {"chance":1, "duration":12, "recharge":30, "skillClass":'Skill_BuffSelfDuration', "trigger":'manual', "type":'buff'}, {"aether resist":30, "chaos resist":30, "cold resist":30, "energy":-66, "fire resist":30, "lightning resist":30})),
	Item('Reinforced Shell', {"block %":8, "blocked damage %":22, "physique":10}, ['shield'], Ability('Blade Ward', {"chance":1, "duration":3, "recharge":12, "skillClass":'Skill_BuffSelfDuration', "trigger":'manual', "type":'buff'}, {"energy":-45, "physical retaliation":350, "pierce resist":30, "shield recovery":100})),
	Item('Resilient Plating', {"armor":24, "defense":26, "pierce resist":15}, ['chest', 'offhand', 'shield', 'shoulders']),
	Item('Restless Remains', {"cast speed":10, "energy":220, "lifesteal %":3}, ['arms']),
	Item('Riftstone', {"chaos":5, "chaos %":25, "physical to chaos":10}, ['axe', 'dagger', 'mace', 'offhand', 'scepter', 'shield', 'sword', 'twohand'], Ability('Void Weapons', {"chance":1, "skillClass":'Skill_BuffSelfToggled', "trigger":'toggle', "type":'buff'}, {"chaos %":75, "pet chaos":8, "pet chaos %":75, "triggered chaos":10})),
	Item('Rigid Shell', {"armor":24, "lightning resist":20, "physique":10}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item('Roiling Blood', {"offense":18, "physical %":8}, ['amulet', 'medal', 'ring']),
	Item('Rotten Heart', {"acid retaliation":75, "offense %":2, "spirit %":2}, ['chest']),
	Item('Runebound Topaz', {"blocked damage %":8, "defense":52, "health":160, "stun resist":10}, ['amulet', 'medal', 'ring']),
	Item('Runestone', {"acid resist":12, "aether resist":12, "elemental resist":12}, ['head']),
	Item('Sacred Plating', {"aether resist":18, "armor absorb":12, "health":210, "vitality resist":14}, ['chest', 'head', 'shoulders']),
	Item('Sanctified Bone', {"chaos resist":12, "vitality resist":18}, ['chest', 'head']),
	Item('Scaled Hide', {"armor":35, "armor absorb":20}, ['chest', 'legs', 'shoulders']),
	Item('Scavenged Plating', {"armor":15}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item('Seal of Ancestry', {"energy/s":1.5, "energy/s %":10, "health %":5, "vitality resist":20}, ['amulet'], Ability('Ancestral Ward', {"chance":1, "recharge":16, "skillClass":'Skill_PassiveOnHitBuffShield', "trigger":'hit', "type":'buff'}, {"damage absorb":9000})),
	Item('Seal of Annihilation', {"attack speed":5, "cast speed":5, "skill cost %":-10, "spirit":20}, ['amulet'], Ability('Item Skill', {"chance":0.15, "duration":5, "recharge":1, "skillClass":'Skill_AttackBuff', "trigger":'critical', "type":'buff'}, {"defense":55, "offense":55})),
	Item('Seal of Blades', {"bleed":[10, 3], "bleed %":50, "lifesteal %":5, "pierce":10, "pierce %":50}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword', 'twohand'], Ability('Whirling Blades', {"chance":1, "skillClass":'Skill_BuffAttackRadiusToggled', "trigger":'toggle', "type":'buff'}, {"armor %":8, "pierce resist":15, "triggered bleed":[145, 1], "triggered pierce":155})),
	Item('Seal of Blight', {"acid %":50, "crit damage":6, "physical to vitality":10, "poison %":50, "vitality":10.5, "vitality %":50, "vitality decay %":50}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword', 'twohand'], Ability('Acid Purge', {"chance":1, "recharge":0.3, "skillClass":'Skill_AttackSpellCone', "trigger":'manual', "type":'attack'}, {"energy":-33, "lifesteal %":6, "triggered acid":232, "triggered poison":[330, 5], "triggered vitality":232, "weapon damage %":36})),
	Item('Seal of Corruption', {"aether":11, "aether %":50, "electrocute %":50, "lightning %":50, "offense":44, "physical to aether":10}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword', 'twohand'], Ability('Item Skill', {"chance":1, "duration":6, "skillClass":'Skill_AttackBuff', "trigger":'manual', "type":'buff'}, {"energy":-66, "triggered aether":255, "triggered lightning":220})),
	Item('Seal of Destruction', {"burn %":50, "crit damage":6, "electrocute %":50, "fire":10.5, "fire %":50, "lightning %":50, "physical to fire":10}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword', 'twohand'], Ability('Stormfire', {"chance":1, "skillClass":'Skill_AttackProjectile', "trigger":'manual', "type":'attack'}, {"energy":-60, "triggered burn":[130, 3], "triggered fire":187, "triggered lightning":218, "weapon damage %":40})),
	Item('Seal of Might', {"aether to physical":25, "bleed %":50, "health":160, "internal %":50, "physical":13, "physical %":50}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword', 'twohand'], Ability('Presence of Might', {"chance":1, "skillClass":'Skill_BuffSelfToggled', "trigger":'toggle', "type":'buff'}, {"armor %":8, "bleed resist":12, "pet armor %":8, "pet bleed resist":12, "pet pierce resist":12, "pet vitality resist":12, "pierce resist":12, "vitality resist":12})),
	Item('Seal of Resonance', {"aether %":50, "elemental":10, "elemental %":50, "health":160, "physical to elemental":10}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword', 'twohand'], Ability('Arcane Resonance', {"chance":1, "skillClass":'Skill_BuffSelfToggled', "trigger":'toggle', "type":'buff'}, {"freeze resist":15, "pet freeze resist":15, "pet petrify resist":15, "pet stun resist":15, "pet trap resist":15, "petrify resist":15, "stun resist":15, "trap resist":15})),
	Item('Seal of Shadows', {"acid":10.5, "acid %":50, "cast speed":4, "physical to acid":10, "pierce %":50, "poison %":50}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword', 'twohand'], Ability('Biting Blades', {"chance":1, "skillClass":'Skill_AttackProjectile', "trigger":'manual', "type":'attack'}, {"energy":-45, "triggered acid":244, "triggered pierce":244, "triggered poison":[100, 2], "weapon damage %":50})),
	Item('Seal of Skies', {"cast speed":4, "cold %":50, "electrocute %":50, "frostburn %":50, "lightning":10.5, "lightning %":50, "physical to lightning":10}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword', 'twohand'], Ability('Chain Lightning', {"chance":1, "skillClass":'Skill_AttackChain', "trigger":'manual', "type":'attack'}, {"energy":-60, "triggered cold":235, "triggered electrocute":[150, 2], "triggered lightning":300.5, "weapon damage %":70})),
	Item('Seal of the Night', {"cold":11, "cold %":50, "frostburn %":50, "offense":44, "physical to cold":10, "pierce %":50}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword', 'twohand'], Ability('Chillspikes', {"chance":1, "skillClass":'Skill_AttackProjectileBurst', "trigger":'manual', "type":'attack'}, {"energy":-60, "triggered cold":106, "triggered frostburn":[175, 3], "triggered pierce":122, "weapon damage %":12})),
	Item('Seal of the Void', {"attack speed":4, "burn %":50, "chaos":10.5, "chaos %":50, "fire %":50, "physical to chaos":10}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword', 'twohand'], Ability('Burning Void', {"chance":1, "skillClass":'Skill_WPAttack_BasicAttack', "trigger":'manual', "type":'attack'}, {"stun %":100, "triggered chaos":120, "triggered fire":122, "weapon damage %":140})),
	Item('Searing Ember', {"fire":3, "fire %":12, "physical to fire":10}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword', 'twohand'], Ability('Fireblast', {"chance":1, "skillClass":'Skill_AttackProjectile', "trigger":'manual', "type":'attack'}, {"energy":-18, "triggered burn":[42, 3], "triggered fire":56, "weapon damage %":20})),
	Item('Serrated Shell', {"physical retaliation":136, "retaliation %":20, "shield recovery":20}, ['shield'], Ability('Brutal Shield Slam', {"chance":1, "recharge":3, "skillClass":'Skill_AttackWeapon', "trigger":'manual', "type":'attack'}, {"energy":-36, "stun %":50, "triggered internal":[260, 5], "triggered physical":315, "weapon damage %":300})),
	Item('Serrated Spike', {"bleed":[3, 3], "bleed %":12, "pierce":3}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword', 'twohand'], Ability('Impaling Weapons', {"chance":1, "skillClass":'Skill_BuffSelfToggled', "trigger":'toggle', "type":'buff'}, {"pet physical":5, "pet physical %":25, "pierce %":25, "triggered pierce":5})),
	Item('Severed Claw', {"internal %":15, "physical":7, "physical %":25}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword', 'twohand'], Ability('Brutal Slam', {"chance":1, "recharge":2, "skillClass":'Skill_AttackWeaponRadius', "trigger":'manual', "type":'attack'}, {"energy":-50, "triggered physical":291, "weapon damage %":180})),
	Item('Shard of Beronath', {"all damage %":18, "elemental":8, "offense":32, "physical to elemental":10}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword', 'twohand'], Ability("Beronath's Fury", {"chance":1, "skillClass":'Skill_WeaponPool_ChargedScaling', "trigger":'manual', "type":'attack'}, {"all damage %":60, "elemental %":60, "energy":-6, "triggered elemental":33, "triggered physical":12, "weapon damage %":124})),
	Item('Silk Swatch', {"bleed resist":18, "pierce resist":18}, ['chest', 'legs', 'shoulders']),
	Item('Silvercore Bolts', {"all damage %":45, "offense":35, "pierce":10}, ['offhand', 'ranged'], Ability('Silver Armament', {"chance":1, "skillClass":'Skill_BuffSelfToggled', "trigger":'toggle', "type":'buff'}, {"all damage %":40, "pet all damage %":40})),
	Item('Soul Shard', {"energy absorb":30, "vitality %":12, "vitality decay %":12, "vitality resist":20}, ['amulet', 'medal', 'ring']),
	Item('Spellscorched Plating', {"elemental resist":15, "health":100, "pierce resist":20}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item('Spellwoven Threads', {"cast speed":8, "offense":34, "spirit":15}, ['arms']),
	Item('Spined Carapace', {"armor":24, "physical retaliation":55, "retaliation %":12}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item('Symbol of Solael', {"chaos":7, "chaos %":35, "energy absorb":33, "physical to chaos":10}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword', 'twohand'], Ability('Item Skill', {"chance":1, "duration":8, "skillClass":'Skill_AttackBuffRadius', "trigger":'manual', "type":'buff'}, {"energy":-60, "reduce chaos resist":10, "reduce vitality resist":10, "triggered chaos":119.5})),
	Item('Tainted Heart', {"aether resist":12, "crit damage":5, "offense":15, "vitality resist":12}, ['amulet', 'medal']),
	Item('Titan Plating', {"armor %":12, "physique %":4, "pierce resist":24, "reflected damage reduction":33}, ['chest', 'head']),
	Item('Ugdenbog Leather', {"acid resist":20, "bleed resist":20, "defense":30}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item('Unholy Inscription', {"bleed resist":15, "lifesteal %":5, "offense":15, "vitality resist":10}, ['arms']),
	Item('Vengeful Wraith', {"cold %":12, "cold retaliation":120, "frostburn %":25, "frostburn duration":30, "offense":36}, ['amulet', 'medal', 'ring']),
	Item('Venom-Tipped Ammo', {"acid":4, "acid %":25, "physical to acid":10, "poison":[4, 5], "poison %":25, "poison duration":10}, ['offhand', 'ranged'], Ability('Noxious Poison Bomb', {"chance":1, "duration":4, "skillClass":'Skill_AttackProjectile', "trigger":'manual', "type":'attack'}, {"duration":{"reduce resist":15}, "energy":-44, "triggered acid":80, "triggered poison":[260, 2], "weapon damage %":15})),
	Item('Vicious Jawbone', {"attack speed":5, "cunning":12, "internal %":20, "physical %":15}, ['amulet', 'medal']),
	Item('Vicious Spikes', {"crit damage":4, "pierce":4, "pierce %":18}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword', 'twohand'], Ability('Empowered Impaling Weapons', {"chance":1, "skillClass":'Skill_BuffSelfToggled', "trigger":'toggle', "type":'buff'}, {"pet physical":8, "pet physical %":75, "pierce %":75, "triggered pierce":10})),
	Item('Vitriolic Gallstone', {"acid":4, "acid %":25, "physical to acid":10, "poison":[4, 5], "poison %":25}, ['axe', 'dagger', 'mace', 'offhand', 'scepter', 'shield', 'sword', 'twohand'], Ability('Envenomed Weapons', {"chance":1, "skillClass":'Skill_BuffSelfToggled', "trigger":'toggle', "type":'buff'}, {"acid %":75, "pet acid %":75, "pet poison":[7, 5], "pet poison %":75, "pet poison duration":20, "poison %":75, "poison duration":20, "triggered poison":[9, 5]})),
	Item('Void-Touched Ammo', {"chaos":5, "chaos %":25, "physical to chaos":10}, ['offhand', 'ranged'], Ability('Chaos Bolt', {"chance":1, "skillClass":'Skill_AttackProjectileBurst', "trigger":'manual', "type":'attack'}, {"energy":-42, "triggered chaos":151, "weapon damage %":12})),
	Item('Wardstone', {"bleed resist":18, "elemental resist":18, "move speed":6}, ['amulet', 'medal']),
	Item('Wrathstone', {"aether":5, "aether %":25, "physical to aether":10}, ['axe', 'dagger', 'mace', 'offhand', 'scepter', 'shield', 'sword', 'twohand'], Ability('Aether Weapons', {"chance":1, "skillClass":'Skill_BuffSelfToggled', "trigger":'toggle', "type":'buff'}, {"aether %":75, "aether retaliation":84, "pet aether":8, "pet aether %":75, "pet aether retaliation":84, "triggered aether":10})),
]

augments = [
	Item('Aether Dust', {"aether":8, "aether %":25}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item('Aetherstorm Powder', {"aether %":35, "elemental resist":10, "lightning %":35}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item("Amatok's Feast", {"bleed %":55, "cold %":55, "defense %":3, "frostburn %":55, "health %":4}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item("Amatok's Tooth", {"bleed %":50, "cold":12, "cold %":50, "defense":70}, ['amulet', 'ring']),
	Item('Arcane Heart Powder', {"aether %":50, "burn %":50, "fire":12, "fire %":50, "offense %":2}, ['amulet', 'ring']),
	Item('Arcanum Dust', {"all damage %":35, "defense":70, "elemental resist":10, "energy/s":2.5}, ['amulet', 'ring']),
	Item('Arkovian Bonemeal', {"vitality":8, "vitality %":25}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item('Arkovian Rose Powder', {"elemental %":18, "elemental resist":10, "energy/s":1}, ['amulet', 'ring']),
	Item("Ateph's Command", {"armor %":8, "bleed":[14, 3], "bleed %":50, "healing %":8}, ['amulet', 'ring']),
	Item("Ateph's Glare", {"cold":12, "cold %":50, "defense %":2, "frostburn %":50, "health":250}, ['amulet', 'ring']),
	Item("Ateph's Promise", {"defense %":3, "electrocute %":50, "health":350, "lightning %":50, "petrify resist":8}, ['amulet', 'ring']),
	Item("Ateph's Will", {"armor %":8, "health %":6, "pet attack speed":8, "pet bleed resist":30}, ['amulet', 'ring']),
	Item("Basilisk's Bite", {"bleed %":50, "health":350, "stun resist":8, "vitality %":50, "vitality decay %":50}, ['amulet', 'ring']),
	Item("Basilisk's Gaze", {"acid %":50, "armor %":12, "armor absorb":10, "chaos %":50, "poison %":50}, ['amulet', 'ring']),
	Item("Beast Tamer's Powder", {"pet all damage %":12, "pet defense %":4}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item("Beastlord's Calling", {"pet all damage %":15, "pet defense %":3, "pet health %":5}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item('Beastmonger Powder', {"defense":20, "pet all damage %":18, "pet elemental resist":20}, ['amulet', 'ring']),
	Item("Beronath's Sacred Step", {"bleed resist":15, "defense":50, "pet bleed resist":30, "pet stun resist":15}, ['amulet', 'ring']),
	Item('Binding Dust', {"pet health %":8, "pet vitality resist":15}, ['amulet', 'ring']),
	Item('Blacksteel Powder', {"fire %":25, "offense":18, "physical %":25}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item('Bladeward Powder', {"pierce resist":12}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item('Blazecore Powder', {"burn":[12, 3], "burn %":36, "electrocute %":36, "fire %":36, "lightning %":36}, ['amulet', 'ring']),
	Item('Blessed Ashes', {"defense":14, "fire resist":15, "lightning resist":15}, ['amulet', 'ring']),
	Item('Blight Beast Pustules', {"acid %":40, "health":200, "pet all damage %":20, "pet armor %":8, "poison %":40}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item('Bloodbound Offering', {"chaos":10, "chaos %":40, "vitality %":40, "vitality decay %":40}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item('Bloodrose Thorn', {"bleed":[12, 3], "bleed %":36, "pierce %":36}, ['amulet', 'ring']),
	Item('Bloodrot Powder', {"acid resist":10, "defense":70, "pet attack speed":10, "pet defense %":4}, ['amulet', 'ring']),
	Item('Bloodscale Powder', {"bleed %":40, "health":200, "health %":4}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item('Boneback Spine', {"bleed %":25, "offense":20, "pierce %":25}, ['amulet', 'ring']),
	Item('Breath of Life', {"health %":4, "health/s %":10, "vitality resist":15}, ['amulet', 'ring']),
	Item("Bysmiel's Control", {"health":250, "pet all damage %":25, "pet armor %":10, "pet crit damage":6}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item("Bysmiel's Cunning", {"health":250, "internal":[12, 5], "internal %":55, "physical %":55, "pierce %":55}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item("Bysmiel's Desert Barb", {"pierce resist":15}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item("Bysmiel's Shroud", {"aether":12, "aether %":55, "internal %":55, "offense":30, "physical %":55}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item("Bysmiel's Silversand", {"defense":16, "health/s":16}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item("Bysmiel's Veiltouch", {"acid resist":12, "aether resist":10}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item("Cairn's Hope", {"bleed resist":18, "energy/s %":15, "health %":3, "health/s %":15}, ['amulet', 'ring']),
	Item('Chillheart Powder', {"cold resist":15, "frostburn %":35, "vitality resist":10}, ['amulet', 'ring']),
	Item('Cinderbark Powder', {"bleed resist":15, "burn %":36, "electrocute %":36, "fire %":36, "lightning %":36}, ['amulet', 'ring']),
	Item('Colossus Spine', {"armor %":6, "armor absorb":5, "physique":30}, ['amulet', 'ring']),
	Item("Conjurer's Powder", {"elemental %":20, "health %":3, "pet all damage %":12}, ['amulet', 'ring']),
	Item('Consecrated Silver', {"chaos resist":12, "physical %":25}, ['amulet', 'ring']),
	Item('Corpsefiend Tentacle', {"aether %":25, "vitality %":25, "vitality resist":10}, ['amulet', 'ring']),
	Item('Coven Black Ash', {"chaos resist":10, "pierce resist":10}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item('Coven Bloodied Ash', {"bleed resist":10, "health/s %":8}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item('Coven Warding Powder', {"elemental resist":9}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item("Coven's Bane", {"acid %":55, "chaos resist":10, "energy/s":1.2, "poison %":55, "vitality %":55, "vitality decay %":55}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item("Coven's Guile", {"cold %":55, "elemental resist":10, "energy/s":1.2, "frostburn %":55, "pierce %":55}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item("Coven's Terror", {"chaos %":55, "health":250, "health %":4, "internal %":55, "physical %":55}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item("Coven's Wit", {"armor %":5, "offense":30, "pet all damage %":25, "pet total speed":4}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item("Creed's Cunning", {"elemental %":35, "energy/s":1, "health":200, "offense":22}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item('Demonbane Powder', {"chaos resist":9, "vitality resist":9}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item('Dermapteran Chitin', {"armor %":4, "pierce resist":8, "stun resist":10}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item('Desert Tongue', {"chaos":10, "chaos %":36, "pet all damage %":18, "pet chaos":4}, ['amulet', 'ring']),
	Item('Divine Flame', {"elemental resist":10, "fire %":25, "lightning %":25}, ['amulet', 'ring']),
	Item("Dranghoul's Breath", {"cold %":40, "frostburn":[10, 3], "frostburn %":40, "internal %":40, "physical %":40}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item("Dreeg's Fiendblood", {"acid resist":12, "chaos resist":10}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item("Dreeg's Foresight", {"chaos resist":10, "elemental %":55, "energy/s":1.2, "health %":4}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item("Dreeg's Omen", {"defense":30}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item("Dreeg's Spinedust", {"acid":12, "acid %":55, "bleed resist":10, "health":250, "poison %":55}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item("Dreeg's Terror", {"chaos":12, "chaos %":55, "pierce resist":10, "vitality %":55, "vitality decay %":55}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item("Dreeg's Veilward", {"aether resist":15, "constitution %":8}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item('Duskbloom', {"armor %":5, "chaos %":40, "defense":20}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item('Eldritch Bloom Powder', {"chaos resist":10, "elemental %":40, "pet all damage %":20, "pet elemental":4}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item("Emblem of Dreeg's Vector", {}, ['medal'], Ability("Dreeg's Vector", {"chance":1, "recharge":5.5, "skillClass":'Skill_AttackRadiusTeleport', "trigger":'manual', "type":'attack'}, {"energy":-70, "triggered acid":220})),
	Item('Emblem of Focused Rage', {}, ['medal'], Ability('Charge', {"chance":1, "recharge":3.5, "skillClass":'Skill_AttackWeaponCharge', "trigger":'manual', "type":'attack'}, {"energy":-33, "move speed":250, "stun %":150, "weapon damage %":200})),
	Item('Emblem of Hranaakian Flight', {}, ['medal']),
	Item('Emblem of Korvan Swiftness', {}, ['medal'], Ability('Korvan Swiftness', {"chance":1, "recharge":4, "skillClass":'Skill_AttackRadiusLeap', "trigger":'manual', "type":'attack'}, {"energy":-40, "triggered fire":220, "weapon damage %":200})),
	Item('Emblem of Kurn Endurance', {}, ['medal']),
	Item('Emblem of Kurn Guile', {}, ['medal']),
	Item("Emblem of Rahn's Might", {}, ['medal'], Ability("Rahn's Might", {"chance":1, "recharge":3, "skillClass":'Skill_AttackPathCharge', "trigger":'manual', "type":'attack'}, {"energy":-45, "move speed":300, "stun %":50, "triggered lightning":287.5, "weapon damage %":205})),
	Item('Emblem of the Agile Huntress', {}, ['medal'], Ability('Disengage', {"chance":1, "recharge":4, "skillClass":'Skill_AttackRadiusDisengage', "trigger":'manual', "type":'attack'}, {"energy":-33})),
	Item('Emblem of the Charging Bull', {}, ['medal'], Ability('Rush', {"chance":1, "recharge":4, "skillClass":'Skill_AttackPathCharge', "trigger":'manual', "type":'attack'}, {"energy":-33, "move speed":300, "stun %":50, "weapon damage %":120})),
	Item('Emblem of the Leaping Mantis', {}, ['medal'], Ability('Leap', {"chance":1, "recharge":5, "skillClass":'Skill_AttackRadiusLeap', "trigger":'manual', "type":'attack'}, {"energy":-33, "stun %":50, "weapon damage %":80})),
	Item('Emblem of the Riftstalker', {}, ['medal'], Ability('Rift Tear', {"chance":1, "recharge":5, "skillClass":'Skill_AttackRadiusTeleport', "trigger":'manual', "type":'attack'}, {"energy":-55})),
	Item('Emblem of the Shadowy Assassin', {}, ['medal'], Ability('Vanish', {"chance":1, "recharge":3.5, "skillClass":'Skill_AttackWeaponBlink', "trigger":'manual', "type":'attack'}, {"energy":-33, "move speed":250, "weapon damage %":200})),
	Item("Empyrion's Touch", {"electrocute":[10, 3], "electrocute %":100, "energy absorb":10, "health/s":20}, ['amulet', 'ring']),
	Item("Essence of Ch'thon", {"chaos %":35, "chaos resist":8, "reduce resist":15, "vitality %":35}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item('Firebloom Powder', {"burn %":35, "health/s":15, "offense":20}, ['amulet', 'ring']),
	Item('Flameweave Powder', {"fire resist":12, "pierce resist":9}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item('Fleshwarp Powder', {"aether %":36, "internal":[12, 5], "internal %":36, "physical %":36}, ['amulet', 'ring']),
	Item('Forgefire', {"aether %":50, "defense":70, "elemental":15, "elemental %":50}, ['amulet', 'ring']),
	Item('Gargoyle Fang', {"cold %":36, "defense":20, "frostburn %":36, "internal %":36, "physical %":36}, ['amulet', 'ring']),
	Item('Gargoyle Scale', {"internal":[10, 5], "internal %":40, "offense":25, "physical %":40}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item('Gazer Eye', {"aether %":25, "aether resist":10, "lightning %":25}, ['amulet', 'ring']),
	Item("Giant's Tusk Powder", {"bleed resist":15, "defense":20, "shield recovery":5}, ['amulet', 'ring']),
	Item('Glacier Dust', {"bleed resist":15, "health/s":24, "pierce resist":15}, ['amulet', 'ring']),
	Item('Glyph of Arcane Insights', {}, ['medal'], Ability('Arcane Rift', {"chance":1, "recharge":5.5, "skillClass":'Skill_AttackRadiusTeleport', "trigger":'manual', "type":'attack'}, {"crit damage":35, "energy":-88, "triggered aether":250, "triggered lightning":250})),
	Item('Glyph of Ashen Wastes', {}, ['medal'], Ability('Chaos Strike', {"chance":1, "recharge":3, "skillClass":'Skill_AttackWeaponBlink', "trigger":'manual', "type":'attack'}, {"energy":-66, "move speed":400, "triggered chaos":350, "triggered vitality":350, "weapon damage %":300})),
	Item('Glyph of Burning Rifts', {}, ['medal'], Ability('Burning Rift', {"chance":1, "recharge":5.5, "skillClass":'Skill_AttackRadiusTeleport', "trigger":'manual', "type":'attack'}, {"energy":-88, "triggered burn":[300, 3], "triggered chaos":180, "triggered fire":180})),
	Item('Glyph of Disorder', {}, ['medal'], Ability('Disorder', {"chance":1, "recharge":3.6, "skillClass":'Skill_AttackRadiusTeleport', "trigger":'manual', "type":'attack'}, {"energy":-88})),
	Item("Glyph of Dreeg's Vector", {}, ['medal'], Ability("Empowered Dreeg's Vector", {"chance":1, "recharge":5.5, "skillClass":'Skill_AttackRadiusTeleport', "trigger":'manual', "type":'attack'}, {"duration":{"defense":120}, "energy":-88, "triggered acid":250, "triggered poison":[250, 2]})),
	Item('Glyph of Ghastly Retreats', {}, ['medal'], Ability('Ghastly Retreat', {"chance":1, "recharge":4, "skillClass":'Skill_AttackRadiusDisengage', "trigger":'manual', "type":'attack'}, {"energy":-45, "lifesteal %":25, "stun %":100, "triggered aether":350})),
	Item('Glyph of Hranaakian Flight', {}, ['medal']),
	Item('Glyph of Incorporeal Winds', {}, ['medal'], Ability('Incorporeal Winds', {"chance":1, "recharge":3, "skillClass":'Skill_AttackPathCharge', "trigger":'manual', "type":'attack'}, {"energy":-50, "move speed":300, "stun %":50, "triggered aether":250, "triggered physical":250, "weapon damage %":220})),
	Item('Glyph of Korvan Swiftness', {}, ['medal'], Ability('Empowered Korvan Swiftness', {"chance":1, "recharge":4, "skillClass":'Skill_AttackRadiusLeap', "trigger":'manual', "type":'attack'}, {"energy":-50, "triggered burn":[250, 3], "triggered fire":250, "weapon damage %":215})),
	Item('Glyph of Kurn Endurance', {}, ['medal']),
	Item('Glyph of Kurn Guile', {}, ['medal']),
	Item("Glyph of Rahn's Might", {}, ['medal'], Ability("Empowered Rahn's Might", {"chance":1, "recharge":3, "skillClass":'Skill_AttackPathCharge', "trigger":'manual', "type":'attack'}, {"energy":-55, "move speed":300, "stun %":70, "triggered electrocute":[300, 3], "triggered lightning":315, "weapon damage %":215})),
	Item('Glyph of Seismic Strength', {}, ['medal'], Ability('Seismic Leap', {"chance":1, "recharge":4, "skillClass":'Skill_AttackRadiusLeap', "trigger":'manual', "type":'attack'}, {"energy":-55, "stun %":80, "triggered bleed":[200, 3], "triggered internal":[200, 3], "triggered physical":250, "weapon damage %":215})),
	Item('Glyph of Spontaneous Blades', {}, ['medal'], Ability('Bladed Rift', {"chance":1, "recharge":5.5, "skillClass":'Skill_AttackRadiusTeleport', "trigger":'manual', "type":'attack'}, {"duration":{"offense":140}, "energy":-88, "triggered pierce":250})),
	Item('Glyph of Sudden Strikes', {}, ['medal'], Ability('Sudden Strike', {"chance":1, "recharge":3, "skillClass":'Skill_AttackWeaponBlink', "trigger":'manual', "type":'attack'}, {"crit damage":40, "energy":-66, "move speed":400, "triggered physical":575, "weapon damage %":300})),
	Item('Glyph of Wayward Souls', {}, ['medal'], Ability('Soul Strike', {"chance":1, "recharge":3, "skillClass":'Skill_AttackWeaponCharge', "trigger":'manual', "type":'attack'}, {"energy":-66, "lifesteal %":20, "move speed":250, "stun %":150, "triggered vitality":400, "triggered vitality decay":[350, 2], "weapon damage %":300})),
	Item('Glyph of the Elusive Assassin', {}, ['medal'], Ability("Assassin's Evasion", {"chance":1, "recharge":4, "skillClass":'Skill_AttackRadiusDisengage', "trigger":'manual', "type":'attack'}, {"energy":-45, "triggered bleed":[400, 2], "triggered pierce":200})),
	Item('Glyph of the Northern Ram', {}, ['medal'], Ability('Ramming Speed', {"chance":1, "recharge":3, "skillClass":'Skill_AttackPathCharge', "trigger":'manual', "type":'attack'}, {"duration":{"slow move":20}, "energy":-50, "move speed":300, "stun %":50, "triggered cold":250, "triggered pierce":250, "weapon damage %":220})),
	Item('Glyph of the Pouncing Manticore', {}, ['medal'], Ability('Manticore Pounce', {"chance":1, "recharge":4, "skillClass":'Skill_AttackRadiusLeap', "trigger":'manual', "type":'attack'}, {"duration":{"defense":130}, "energy":-55, "triggered acid":200, "triggered pierce":200, "weapon damage %":215})),
	Item('Glyph of the Ravenous Wendigo', {}, ['medal'], Ability('Wendigo Rush', {"chance":1, "recharge":3, "skillClass":'Skill_AttackPathCharge', "trigger":'manual', "type":'attack'}, {"energy":-50, "lifesteal %":12, "move speed":300, "stun %":50, "triggered bleed":[300, 3], "triggered vitality":250, "weapon damage %":220})),
	Item('Glyph of the Rising Phoenix', {}, ['medal'], Ability('Phoenix Rise', {"chance":1, "recharge":4, "skillClass":'Skill_AttackRadiusDisengage', "trigger":'manual', "type":'attack'}, {"duration":{"defense":180}, "energy":-45, "triggered burn":[400, 3]})),
	Item('Glyph of the Scorpion Tail', {}, ['medal'], Ability('Scorpion Strike', {"chance":1, "recharge":3, "skillClass":'Skill_AttackWeaponCharge', "trigger":'manual', "type":'attack'}, {"duration":{"offense":80}, "energy":-66, "move speed":250, "stun %":150, "triggered acid":400, "triggered poison":[350, 3], "weapon damage %":300})),
	Item('Glyph of the Stormclap', {}, ['medal'], Ability('Stormclap', {"chance":1, "recharge":4, "skillClass":'Skill_AttackRadiusLeap', "trigger":'manual', "type":'attack'}, {"crit damage":15, "energy":-55, "triggered cold":200, "triggered electrocute":[250, 3], "triggered lightning":200, "weapon damage %":215})),
	Item('Glyph of the Winter Fox', {}, ['medal'], Ability('Outfox', {"chance":1, "recharge":4, "skillClass":'Skill_AttackRadiusDisengage', "trigger":'manual', "type":'attack'}, {"duration":{"slow move":40}, "energy":-45, "triggered frostburn":[400, 3]})),
	Item('Gryphon Talon', {"bleed %":40, "health %":4, "vitality %":40, "vitality decay %":40}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item('Hammerfall Powder', {"defense":70, "internal %":50, "physical %":50, "pierce":10, "pierce %":50}, ['amulet', 'ring']),
	Item('Haunted Powder', {"aether %":40, "electrocute %":40, "lightning %":40, "stun resist":10}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item('Heart of Ugdenbog', {"blocked damage %":25, "health %":6, "internal":[14, 5], "petrify resist":8}, ['amulet', 'ring']),
	Item("Herald's Glare", {"health %":6, "pet chaos %":60, "pet pierce resist":30, "pet slow resist":15}, ['amulet', 'ring']),
	Item("Hexxer's Bloom", {"aether %":36, "electrocute %":36, "lightning %":36, "pet offense %":3, "petrify resist":8}, ['amulet', 'ring']),
	Item("Hexxer's Delight", {"elemental %":36, "health":200, "offense":25}, ['amulet', 'ring']),
	Item("Hexxer's Kiss", {"burn %":40, "chaos %":40, "fire %":40, "reduce resist":15}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item('Hranaak Feather Ash', {"aether %":50, "armor %":12, "chaos resist":15, "vitality %":50, "vitality decay %":50}, ['amulet', 'ring']),
	Item('Hranaak Incense', {"aether %":55, "defense %":3, "offense %":3, "vitality %":55, "vitality decay %":55}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item('Imp Eye Powder', {"aether":10, "aether %":40, "vitality %":40, "vitality decay %":40}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item('Infernal Dust', {"burn":[10, 3], "burn %":100, "elemental resist":12, "offense":25}, ['amulet', 'ring']),
	Item("Irrah's Blood", {"aether resist":15, "defense":70, "vitality %":50, "vitality decay":[15, 3], "vitality decay %":50}, ['amulet', 'ring']),
	Item("Irrah's Dominion", {"aether resist":10, "chaos resist":10, "pet crit damage":8, "pet poison %":60}, ['amulet', 'ring']),
	Item("Irrah's Patience", {"armor %":6, "health":350, "health %":5, "petrify resist":8}, ['amulet', 'ring']),
	Item("Irrah's Soulfire", {"aether":12, "aether %":50, "burn %":50, "defense":70, "fire %":50}, ['amulet', 'ring']),
	Item("Irrah's Venomtongue", {"acid %":50, "bleed %":50, "elemental resist":15, "offense":75, "poison %":50}, ['amulet', 'ring']),
	Item("Keeper's Binding Dust", {"pet freeze resist":20, "pet stun resist":20, "pet vitality resist":18, "vitality %":30}, ['amulet', 'ring']),
	Item("Keeper's Essence", {"armor %":4, "defense":20, "elemental %":36}, ['amulet', 'ring']),
	Item('Kingsguard Powder', {"acid resist":12, "pierce resist":9}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item('Korvan Cactus Powder', {"acid %":40, "health":200, "poison %":40, "vitality %":40, "vitality decay %":40}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item('Korvan Sunpowder', {"burn":[10, 3], "burn %":40, "fire %":40, "internal %":40, "physical %":40}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item("Kurn Giant's Heart", {"healing %":6, "health/s %":8}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item('Kurn Roc Eye', {"armor %":8, "healing %":6}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item('Kurn Yeti Horn', {"healing %":6, "health":150}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item("Kymon's Blessing", {"fire resist":18}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item("Kymon's Conduit", {"lightning resist":18}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item("Kymon's Fury", {"bleed %":30, "defense %":2, "physical %":30, "reflected damage reduction":10}, ['amulet', 'ring']),
	Item("Kymon's Vision", {"chaos resist":12, "electrocute %":30, "lightning %":30, "offense":25}, ['amulet', 'ring']),
	Item("Kymon's Will", {"burn %":30, "defense %":2, "fire %":30}, ['amulet', 'ring']),
	Item('Machinist Powder', {"armor %":5, "internal %":40, "physical %":40, "pierce %":40}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item('Magecap Powder', {"burn %":36, "cold %":36, "fire %":36, "freeze resist":8, "frostburn %":36}, ['amulet', 'ring']),
	Item("Malkadarr's Chillbane", {"frostburn":[10, 3], "frostburn %":100, "health":150, "offense":25}, ['amulet', 'ring']),
	Item('Malmouth Fortifying Powder', {"health/s %":8, "vitality resist":10}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item('Malmouth Soulguard Powder', {"aether resist":10, "pierce resist":10}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item('Malmouth Woundsear Powder', {"bleed resist":10, "vitality resist":10}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item("Malmouth's Heart", {"burn %":55, "electrocute %":55, "fire %":55, "health":250, "lightning":12, "lightning %":55}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item("Malmouth's Redemption", {"aether resist":10, "armor %":5, "cold":12, "cold %":55, "frostburn %":55}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item("Malmouth's Soul", {"aether %":55, "elemental":12, "elemental %":55, "pierce resist":10}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item("Malmouth's Will", {"electrocute %":55, "health":250, "internal %":55, "lightning %":55, "physical %":55, "vitality resist":10}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item('Mange Powder', {"bleed %":40, "defense":20, "vitality %":40, "vitality decay %":40}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item("Mankind's Vigil", {"aether resist":9, "chaos resist":9}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item('Manticore Venom', {"poison":[8, 5], "poison %":25}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item("Mender's Powder", {"pet aether resist":20, "pet chaos resist":20, "pet health %":10}, ['amulet', 'ring']),
	Item("Menhir's Blessing", {"armor %":5, "physique":17, "stun %":10}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item("Mogdrogen's Bite", {"acid %":55, "defense %":3, "offense %":3, "pierce %":55, "poison %":55}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item("Mogdrogen's Blessing", {"pet attack speed":5, "pet health %":5, "pet offense %":3}, ['amulet', 'ring']),
	Item("Mogdrogen's Boon", {"acid resist":15, "health %":6, "reflected damage reduction":25, "shield recovery":8}, ['amulet', 'ring']),
	Item("Mogdrogen's Sanctity", {"elemental resist":12, "health":180, "health/s":20}, ['amulet', 'ring']),
	Item("Mogdrogen's Touch", {"acid resist":12, "vitality resist":9}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item('Mortal Coil', {"cold %":25, "frostburn %":25, "health":150}, ['amulet', 'ring']),
	Item("Nature's Harvest", {"health %":3, "offense":55, "poison %":35}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item("Nature's Wrath", {"acid %":30, "offense %":2, "poison %":30}, ['amulet', 'ring']),
	Item('Necrotic Flesh', {"bleed resist":15, "vitality %":25, "vitality decay %":25}, ['amulet', 'ring']),
	Item('Nightshade Powder', {"cold resist":12, "pierce resist":9}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item('Nightsteel Polish', {"cold %":36, "frostburn %":36, "pierce":10, "pierce %":36}, ['amulet', 'ring']),
	Item("Oleron's Fervor", {"all damage %":200, "bleed %":35, "physical %":35, "pierce resist":10}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item("Osyr's Fortitude", {"blocked damage %":25, "fire retaliation":104, "health":350, "retaliation %":25}, ['amulet', 'ring']),
	Item("Osyr's Guidance", {"energy/s":1.5, "offense %":3, "pet crit damage":6, "pet offense %":3}, ['amulet', 'ring']),
	Item("Osyr's Temper", {"chaos":12, "chaos %":50, "defense":50, "offense":55}, ['amulet', 'ring']),
	Item("Osyr's Wisdom", {"bleed resist":15, "elemental %":50, "offense %":3, "vitality resist":15}, ['amulet', 'ring']),
	Item("Outcast's Bastion", {"aether resist":8, "chaos resist":8, "defense":10}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item("Outcast's Deathtouch", {"health":200, "vitality":10, "vitality %":35, "vitality decay %":35}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item("Outcast's Elemental Scales", {"cold resist":12, "fire resist":12}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item("Outcast's Frostbite", {"cold %":35, "frostburn %":35, "health":200}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item("Outcast's Inferno", {"burn %":35, "fire %":35, "fire resist":12, "health":200}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item("Outcast's Might", {"aether resist":8, "health":200, "physical %":35, "pierce %":25}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item("Outcast's Riftstorm", {"chaos %":35, "energy/s":1, "health":200, "offense":22}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item("Outcast's Skyguard Powder", {}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item("Outcast's Thunder", {"electrocute %":35, "health":200, "lightning %":35}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item("Outcast's Venom", {"acid":10, "acid %":35, "health":200, "poison %":35}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item("Outcast's Warding Powder", {"aether resist":12}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item("Outcast's Wrath", {"aether %":35, "health":200, "offense":22}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item("Overseer's Gaze", {"aether resist":15, "lightning %":30, "offense":25, "stun %":10}, ['amulet', 'ring']),
	Item('Oxwhip Powder', {"offense":20, "pet acid resist":20, "pet all damage %":18}, ['amulet', 'ring']),
	Item('Potent Aether Dust', {"aether":18, "aether %":60}, ['ranged', 'twohand']),
	Item('Potent Aetherstorm Powder', {"aether %":80, "elemental resist":20, "lightning %":80}, ['ranged', 'twohand']),
	Item("Potent Amatok's Feast", {"bleed %":120, "cold %":120, "defense %":6, "frostburn %":120, "health %":8}, ['ranged', 'twohand']),
	Item('Potent Arkovian Bonemeal', {"vitality":18, "vitality %":60}, ['ranged', 'twohand']),
	Item("Potent Beast Tamer's Powder", {"pet all damage %":28, "pet defense %":8}, ['ranged', 'twohand']),
	Item("Potent Beastlord's Calling", {"pet all damage %":32, "pet defense %":6, "pet health %":10}, ['ranged', 'twohand']),
	Item('Potent Blacksteel Powder', {"fire %":60, "offense":40, "physical %":60}, ['ranged', 'twohand']),
	Item('Potent Blight Beast Pustules', {"acid %":90, "health":440, "pet all damage %":45, "pet armor %":16, "poison %":90}, ['ranged', 'twohand']),
	Item('Potent Bloodbound Offering', {"chaos":22, "chaos %":90, "vitality %":90, "vitality decay %":90}, ['ranged', 'twohand']),
	Item('Potent Bloodscale Powder', {"bleed %":90, "health":440, "health %":8}, ['ranged', 'twohand']),
	Item("Potent Bysmiel's Control", {"health":550, "pet all damage %":55, "pet armor %":20, "pet crit damage":12}, ['ranged', 'twohand']),
	Item("Potent Bysmiel's Cunning", {"health":550, "internal":[25, 5], "internal %":120, "physical %":120, "pierce %":120}, ['ranged', 'twohand']),
	Item("Potent Bysmiel's Shroud", {"aether":25, "aether %":120, "internal %":120, "offense":60, "physical %":120}, ['ranged', 'twohand']),
	Item("Potent Coven's Bane", {"acid %":120, "chaos resist":20, "energy/s":2.4, "poison %":120, "vitality %":120, "vitality decay %":120}, ['ranged', 'twohand']),
	Item("Potent Coven's Guile", {"cold %":120, "elemental resist":20, "energy/s":2.4, "frostburn %":120, "pierce %":120}, ['ranged', 'twohand']),
	Item("Potent Coven's Terror", {"chaos %":120, "health":550, "health %":8, "internal %":120, "physical %":120}, ['ranged', 'twohand']),
	Item("Potent Coven's Wit", {"armor %":10, "offense":60, "pet all damage %":55, "pet total speed":8}, ['ranged', 'twohand']),
	Item("Potent Creed's Cunning", {"elemental %":80, "energy/s":2, "health":440, "offense":45}, ['ranged', 'twohand']),
	Item('Potent Dermapteran Chitin', {"armor %":8, "pierce resist":16, "stun resist":20}, ['ranged', 'twohand']),
	Item("Potent Dranghoul's Breath", {"cold %":90, "frostburn":[22, 3], "frostburn %":90, "internal %":90, "physical %":90}, ['ranged', 'twohand']),
	Item("Potent Dreeg's Foresight", {"chaos resist":20, "elemental %":120, "energy/s":2.4, "health %":8}, ['ranged', 'twohand']),
	Item("Potent Dreeg's Spinedust", {"acid":25, "acid %":120, "bleed resist":20, "health":550, "poison %":120}, ['ranged', 'twohand']),
	Item("Potent Dreeg's Terror", {"chaos":25, "chaos %":120, "pierce resist":20, "vitality %":120, "vitality decay %":120}, ['ranged', 'twohand']),
	Item('Potent Duskbloom', {"armor %":10, "chaos %":90, "defense":40}, ['ranged', 'twohand']),
	Item('Potent Eldritch Bloom Powder', {"chaos resist":20, "elemental %":90, "pet all damage %":45, "pet elemental":8}, ['ranged', 'twohand']),
	Item("Potent Essence of Ch'thon", {"chaos %":80, "chaos resist":16, "reduce resist":15, "vitality %":80}, ['ranged', 'twohand']),
	Item('Potent Gargoyle Scale', {"internal":[22, 5], "internal %":90, "offense":50, "physical %":90}, ['ranged', 'twohand']),
	Item('Potent Gryphon Talon', {"bleed %":90, "health %":8, "vitality %":90, "vitality decay %":90}, ['ranged', 'twohand']),
	Item('Potent Haunted Powder', {"aether %":90, "electrocute %":90, "lightning %":90, "stun resist":20}, ['ranged', 'twohand']),
	Item("Potent Hexxer's Kiss", {"burn %":90, "chaos %":90, "fire %":90, "reduce resist":15}, ['ranged', 'twohand']),
	Item('Potent Hranaak Incense', {"aether %":120, "defense %":6, "offense %":6, "vitality %":120, "vitality decay %":120}, ['ranged', 'twohand']),
	Item('Potent Imp Eye Powder', {"aether":22, "aether %":90, "vitality %":90, "vitality decay %":90}, ['ranged', 'twohand']),
	Item('Potent Korvan Cactus Powder', {"acid %":90, "health":440, "poison %":90, "vitality %":90, "vitality decay %":90}, ['ranged', 'twohand']),
	Item('Potent Korvan Sunpowder', {"burn":[22, 3], "burn %":90, "fire %":90, "internal %":90, "physical %":90}, ['ranged', 'twohand']),
	Item('Potent Machinist Powder', {"armor %":10, "internal %":90, "physical %":90, "pierce %":90}, ['ranged', 'twohand']),
	Item("Potent Malmouth's Heart", {"burn %":120, "electrocute %":120, "fire %":120, "health":550, "lightning":25, "lightning %":120}, ['ranged', 'twohand']),
	Item("Potent Malmouth's Redemption", {"aether resist":20, "armor %":10, "cold":25, "cold %":120, "frostburn %":120}, ['ranged', 'twohand']),
	Item("Potent Malmouth's Soul", {"aether %":120, "elemental":25, "elemental %":120, "pierce resist":20}, ['ranged', 'twohand']),
	Item("Potent Malmouth's Will", {"electrocute %":120, "health":550, "internal %":120, "lightning %":120, "physical %":120, "vitality resist":20}, ['ranged', 'twohand']),
	Item('Potent Mange Powder', {"bleed %":90, "defense":40, "vitality %":90, "vitality decay %":90}, ['ranged', 'twohand']),
	Item('Potent Manticore Venom', {}, ['ranged', 'twohand']),
	Item("Potent Menhir's Blessing", {"armor %":10, "physique":35, "stun %":20}, ['ranged', 'twohand']),
	Item("Potent Mogdrogen's Bite", {"acid %":120, "defense %":6, "offense %":6, "pierce %":120, "poison %":120}, ['ranged', 'twohand']),
	Item("Potent Nature's Harvest", {"health %":7, "offense":55, "poison %":80}, ['ranged', 'twohand']),
	Item("Potent Oleron's Fervor", {"all damage %":500, "bleed %":80, "physical %":80, "pierce resist":20}, ['ranged', 'twohand']),
	Item("Potent Outcast's Bastion", {"aether resist":16, "chaos resist":16, "defense":22}, ['ranged', 'twohand']),
	Item("Potent Outcast's Deathtouch", {"health":440, "vitality":22, "vitality %":80, "vitality decay %":80}, ['ranged', 'twohand']),
	Item("Potent Outcast's Frostbite", {"cold %":80, "frostburn %":80, "health":440}, ['ranged', 'twohand']),
	Item("Potent Outcast's Inferno", {"burn %":80, "fire %":80, "fire resist":24, "health":440}, ['ranged', 'twohand']),
	Item("Potent Outcast's Might", {"aether resist":16, "health":440, "physical %":80, "pierce %":60}, ['ranged', 'twohand']),
	Item("Potent Outcast's Riftstorm", {"chaos %":80, "energy/s":2, "health":440, "offense":45}, ['ranged', 'twohand']),
	Item("Potent Outcast's Thunder", {"electrocute %":80, "health":440, "lightning %":80}, ['ranged', 'twohand']),
	Item("Potent Outcast's Venom", {"acid":22, "acid %":80, "health":440, "poison %":80}, ['ranged', 'twohand']),
	Item("Potent Outcast's Wrath", {"aether %":80, "health":440, "offense":45}, ['ranged', 'twohand']),
	Item('Potent Primordial Ash', {"burn %":120, "fire %":120, "fire retaliation":240, "health %":8, "retaliation %":70}, ['ranged', 'twohand']),
	Item('Potent Raincaller Powder', {"electrocute %":60, "lightning %":60, "offense":40}, ['ranged', 'twohand']),
	Item("Potent Ravager's Breath", {"acid %":120, "health":550, "pierce %":120, "poison":[25, 5], "poison %":120}, ['ranged', 'twohand']),
	Item("Potent Ravager's Eye", {"defense %":6, "health %":8, "pet all damage %":55, "pet offense %":6}, ['ranged', 'twohand']),
	Item("Potent Ravager's Harvest", {"bleed %":120, "health":550, "vitality":25, "vitality %":120, "vitality decay %":120}, ['ranged', 'twohand']),
	Item("Potent Ravager's Rage", {"aether %":120, "burn %":120, "fire":25, "fire %":120, "vitality resist":20}, ['ranged', 'twohand']),
	Item('Potent Sandclaw Fang', {"bleed":[22, 3], "bleed %":90, "pet all damage %":45, "pet bleed":[8, 3]}, ['ranged', 'twohand']),
	Item('Potent Scarabshell Powder', {"aether %":90, "electrocute %":90, "lightning %":90, "offense":50}, ['ranged', 'twohand']),
	Item("Potent Solael's Glare", {"cold %":120, "electrocute %":120, "frostburn %":120, "health":550, "lightning %":120, "pierce resist":20}, ['ranged', 'twohand']),
	Item("Potent Solael's Vision", {"burn %":120, "electrocute %":120, "fire %":120, "health":550, "lightning %":120, "vitality resist":20}, ['ranged', 'twohand']),
	Item("Potent Solael's Voracity", {"bleed %":120, "health":550, "pierce":25, "pierce %":120}, ['ranged', 'twohand']),
	Item('Potent Solar Radiance', {"energy absorb":20, "fire":22, "fire %":80, "offense":45}, ['ranged', 'twohand']),
	Item('Potent Sparkbloom Powder', {"elemental":22, "elemental %":90, "offense":50, "pet attack speed":6}, ['ranged', 'twohand']),
	Item('Potent Spikeshell Powder', {"acid %":90, "cold %":90, "frostburn %":90, "offense":50, "pet health %":12, "poison %":90}, ['ranged', 'twohand']),
	Item('Potent Stardust', {"cold %":90, "electrocute %":90, "frostburn %":90, "health %":8, "lightning %":90}, ['ranged', 'twohand']),
	Item('Potent Stonetusk Hoof', {"armor":80, "internal %":60, "physical %":60}, ['ranged', 'twohand']),
	Item("Potent Stormcaller's Ash", {"aether %":90, "defense":40, "electrocute %":90, "lightning %":90}, ['ranged', 'twohand']),
	Item('Potent Troll Wart Powder', {"health %":7, "health/s":36, "health/s %":16}, ['ranged', 'twohand']),
	Item("Potent Ulgrim's Guile", {}, ['ranged', 'twohand']),
	Item('Potent Viper Venom', {"acid %":90, "cold %":90, "frostburn %":90, "poison":[22, 5], "poison %":90}, ['ranged', 'twohand']),
	Item('Potent Void Tar', {"armor %":10, "chaos %":90, "health %":8}, ['ranged', 'twohand']),
	Item('Potent Voidbeast Powder', {"chaos %":60, "offense":40, "vitality %":60}, ['ranged', 'twohand']),
	Item('Potent Voidvine Powder', {"chaos resist":12, "fire":18, "fire %":60}, ['ranged', 'twohand']),
	Item('Potent Wendigo Fur', {"health":440, "internal %":90, "physical %":90, "vitality %":90, "vitality decay %":90}, ['ranged', 'twohand']),
	Item('Potent Whipvine Powder', {"bleed %":90, "internal %":90, "physical":22, "physical %":90}, ['ranged', 'twohand']),
	Item('Potent Winterbloom Powder', {"cold %":60, "frostburn %":60, "offense":40}, ['ranged', 'twohand']),
	Item("Potent Witch's Powder", {"pet attack speed":12, "pet offense %":6}, ['ranged', 'twohand']),
	Item('Primordial Ash', {"burn %":55, "fire %":55, "fire retaliation":110, "health %":4, "retaliation %":30}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item('Raincaller Powder', {"electrocute %":25, "lightning %":25, "offense":18}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item("Ravager's Breath", {"acid %":55, "health":250, "pierce %":55, "poison":[12, 5], "poison %":55}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item("Ravager's Eye", {"defense %":3, "health %":4, "pet all damage %":25, "pet offense %":3}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item("Ravager's Gift", {"armor %":12, "blocked damage %":25, "shield recovery":8, "vitality resist":15}, ['amulet', 'ring']),
	Item("Ravager's Harvest", {"bleed %":55, "health":250, "vitality":12, "vitality %":55, "vitality decay %":55}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item("Ravager's Rage", {"aether %":55, "burn %":55, "fire":12, "fire %":55, "vitality resist":10}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item("Rhowan's Resolve", {"acid retaliation":75, "armor absorb":2, "physical %":30, "retaliation %":16}, ['amulet', 'ring']),
	Item("Rhowan's Wisdom", {"cast speed":2, "elemental %":30, "elemental resist":12, "spirit %":2}, ['amulet', 'ring']),
	Item('Rifthound Salts', {"pet chaos resist":8, "pet elemental resist":15, "pet total speed":3}, ['amulet', 'ring']),
	Item('Rimethorn Ash', {"acid resist":15, "health %":4, "shield recovery":5}, ['amulet', 'ring']),
	Item('Ritual Salts', {"burn %":70, "electrocute %":70, "frostburn %":70}, ['amulet', 'ring']),
	Item('Rotbloom Powder', {"chaos %":25, "health %":3, "vitality %":25}, ['amulet', 'ring']),
	Item('Rotflesh Powder', {"acid %":36, "bleed resist":15, "life leech resist":15, "poison %":36, "vitality %":36, "vitality decay %":36}, ['amulet', 'ring']),
	Item('Rotgut Venom', {"acid":12, "acid %":50, "bleed %":50, "defense":70, "poison %":50}, ['amulet', 'ring']),
	Item('Rotvine Powder', {"cold %":36, "frostburn %":36, "offense":25, "vitality %":36, "vitality decay %":36}, ['amulet', 'ring']),
	Item("Rune of Amatok's Breath", {}, ['medal'], Ability("Amatok's Breath", {"chance":1, "recharge":2.5, "skillClass":'Skill_AttackPathCharge', "trigger":'manual', "type":'attack'}, {"energy":-66, "move speed":300, "triggered cold":375, "triggered frostburn":[350, 2], "weapon damage %":240})),
	Item('Rune of Astral Rifts', {}, ['medal'], Ability('Astral Rift', {"chance":1, "recharge":4.8, "skillClass":'Skill_AttackRadiusTeleport', "trigger":'manual', "type":'attack'}, {"energy":-120, "triggered aether":300, "triggered fire":300})),
	Item('Rune of Blazing Ends', {}, ['medal'], Ability('Blazing Charge', {"chance":1, "recharge":3, "skillClass":'Skill_AttackWeaponCharge', "trigger":'manual', "type":'attack'}, {"crit damage":25, "energy":-90, "move speed":300, "stun %":150, "triggered burn":[400, 5], "triggered chaos":400, "triggered fire":400, "weapon damage %":380})),
	Item('Rune of Dark Desires', {}, ['medal'], Ability('Dark Desires', {"chance":1, "recharge":2.6, "skillClass":'Skill_AttackWeaponBlink', "trigger":'manual', "type":'attack'}, {"duration":{"defense":180}, "energy":-90, "move speed":500, "triggered chaos":750, "weapon damage %":340})),
	Item('Rune of Displacement', {}, ['medal'], Ability('Displacement', {"chance":1, "recharge":3.2, "skillClass":'Skill_AttackRadiusTeleport', "trigger":'manual', "type":'attack'}, {"energy":-120})),
	Item("Rune of Dread's Wake", {}, ['medal'], Ability("Dread's Wake", {"chance":1, "recharge":3.5, "skillClass":'Skill_AttackRadiusLeap', "trigger":'manual', "type":'attack'}, {"duration":{"slow move":20}, "energy":-70, "triggered bleed":[350, 2], "triggered pierce":300, "weapon damage %":260})),
	Item("Rune of Dreeg's Vector", {}, ['medal'], Ability("Masterful Dreeg's Vector", {"chance":1, "recharge":5.5, "skillClass":'Skill_AttackRadiusTeleport', "trigger":'manual', "type":'attack'}, {"crit damage":25, "duration":{"defense":150}, "energy":-100, "triggered acid":300, "triggered poison":[300, 2]})),
	Item("Rune of Dreeg's Wounds", {}, ['medal'], Ability("Dreeg's Wounds", {"chance":1, "recharge":3.5, "skillClass":'Skill_AttackRadiusLeap', "trigger":'manual', "type":'attack'}, {"energy":-70, "triggered acid":300, "triggered vitality":300, "weapon damage %":260})),
	Item('Rune of Eldritch Instability', {}, ['medal'], Ability('Eldritch Instability', {"chance":1, "recharge":3.5, "skillClass":'Skill_AttackRadiusLeap', "trigger":'manual', "type":'attack'}, {"energy":-70, "triggered acid":250, "triggered physical":250, "weapon damage %":275})),
	Item('Rune of Fallen Kings', {}, ['medal'], Ability('Will of the Fallen Kings', {"chance":1, "recharge":2.5, "skillClass":'Skill_AttackPathCharge', "trigger":'manual', "type":'attack'}, {"crit damage":33, "energy":-66, "move speed":300, "triggered aether":500, "weapon damage %":240})),
	Item('Rune of Hranaakian Flight', {}, ['medal']),
	Item("Rune of Ishtak's Mercy", {}, ['medal'], Ability("Ishtak's Mercy", {"chance":1, "recharge":2, "skillClass":'Skill_AttackRadiusDisengage', "trigger":'manual', "type":'attack'}, {"duration":{"offense":180}, "energy":-60})),
	Item('Rune of Korvan Swiftness', {}, ['medal'], Ability('Masterful Korvan Swiftness', {"chance":1, "recharge":4, "skillClass":'Skill_AttackRadiusLeap', "trigger":'manual', "type":'attack'}, {"crit damage":25, "energy":-66, "triggered burn":[280, 3], "triggered fire":300, "weapon damage %":220})),
	Item('Rune of Kurn Endurance', {}, ['medal']),
	Item('Rune of Kurn Guile', {}, ['medal']),
	Item("Rune of Murmur's Kiss", {}, ['medal'], Ability("Murmur's Kiss", {"chance":1, "recharge":3, "skillClass":'Skill_AttackRadiusDisengage', "trigger":'manual', "type":'attack'}, {"duration":{"defense":220}, "energy":-60, "triggered acid":220, "triggered cold":220})),
	Item("Rune of Nadaan's Strike", {}, ['medal'], Ability("Nadaan's Strike", {"chance":1, "recharge":4.8, "skillClass":'Skill_AttackRadiusTeleport', "trigger":'manual', "type":'attack'}, {"crit damage":45, "energy":-120, "triggered physical":300, "triggered pierce":300, "weapon damage %":150})),
	Item("Rune of Rahn's Might", {}, ['medal'], Ability("Masterful Rahn's Might", {"chance":1, "recharge":3, "skillClass":'Skill_AttackPathCharge', "trigger":'manual', "type":'attack'}, {"crit damage":25, "energy":-60, "move speed":300, "stun %":80, "triggered electrocute":[325, 3], "triggered lightning":340, "weapon damage %":220})),
	Item("Rune of Ultos' Arrival", {}, ['medal'], Ability("Ultos' Arrival", {"chance":1, "recharge":4.8, "skillClass":'Skill_AttackRadiusTeleport', "trigger":'manual', "type":'attack'}, {"duration":{"slow move":30}, "energy":-120, "triggered cold":250, "triggered electrocute":[300, 3], "triggered lightning":250})),
	Item("Rune of Ulzaad's Madness", {}, ['medal'], Ability("Ulzaad's Madness", {"chance":1, "recharge":3, "skillClass":'Skill_AttackRadiusDisengage', "trigger":'manual', "type":'attack'}, {"energy":-60, "triggered physical":250, "triggered pierce":250})),
	Item("Rune of Ulzuin's Fall", {}, ['medal'], Ability("Ulzuin's Fall", {"chance":1, "recharge":3.5, "skillClass":'Skill_AttackRadiusLeap', "trigger":'manual', "type":'attack'}, {"energy":-70, "stun %":250, "triggered aether":300, "triggered fire":300, "weapon damage %":260})),
	Item('Rune of Vampiric Shadows', {}, ['medal'], Ability('Vampiric Shadows', {"chance":1, "recharge":2.6, "skillClass":'Skill_AttackWeaponBlink', "trigger":'manual', "type":'attack'}, {"energy":-90, "lifesteal %":25, "move speed":500, "triggered bleed":[400, 2], "triggered vitality":600, "weapon damage %":340})),
	Item('Rune of Violent Delights', {}, ['medal'], Ability('Violent Delights', {"chance":1, "recharge":2.5, "skillClass":'Skill_AttackPathCharge', "trigger":'manual', "type":'attack'}, {"energy":-66, "move speed":300, "triggered bleed":[350, 2], "triggered physical":375, "weapon damage %":240})),
	Item('Rune of Wretched Desires', {}, ['medal'], Ability('Wretched Desires', {"chance":1, "recharge":3, "skillClass":'Skill_AttackRadiusDisengage', "trigger":'manual', "type":'attack'}, {"energy":-60, "triggered chaos":350})),
	Item('Rune of the Dark Progenitor', {}, ['medal'], Ability('Upon Rylok Wings', {"chance":1, "recharge":3.5, "skillClass":'Skill_AttackRadiusLeap', "trigger":'manual', "type":'attack'}, {"duration":{"defense":170, "offense":170}, "energy":-70, "triggered chaos":375, "weapon damage %":260})),
	Item('Rune of the Stormtitan', {}, ['medal'], Ability("Stormtitan's Charge", {"chance":1, "recharge":3, "skillClass":'Skill_AttackWeaponCharge', "trigger":'manual', "type":'attack'}, {"energy":-90, "move speed":300, "stun %":200, "triggered electrocute":[400, 3], "triggered lightning":555, "weapon damage %":400})),
	Item('Rune of the Typhoon', {}, ['medal'], Ability('Typhoon', {"chance":1, "recharge":3, "skillClass":'Skill_AttackRadiusDisengage', "trigger":'manual', "type":'attack'}, {"duration":{"slow move":50}, "energy":-60, "triggered electrocute":[300, 3], "triggered frostburn":[300, 3]})),
	Item('Sagethorn Powder', {"bleed %":36, "chaos resist":15, "pierce %":36}, ['amulet', 'ring']),
	Item('Sandclaw Fang', {"bleed":[10, 3], "bleed %":40, "pet all damage %":20, "pet bleed":[4, 3]}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item('Sandclaw Scale', {"aether resist":15, "health":200, "pet crit damage":4, "pet health %":8}, ['amulet', 'ring']),
	Item('Scarabshell Powder', {"aether %":40, "electrocute %":40, "lightning %":40, "offense":25}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item('Scorpius Venom', {"acid":10, "acid %":36, "pierce %":36, "poison %":36}, ['amulet', 'ring']),
	Item('Skyshard Powder', {"cold %":50, "electrocute %":50, "frostburn %":50, "lightning":12, "lightning %":50, "offense":75}, ['amulet', 'ring']),
	Item('Slith Venom', {"acid resist":15, "acid retaliation":54, "bleed resist":15, "retaliation %":10}, ['amulet', 'ring']),
	Item('Slithweed Powder', {"acid %":25, "defense":14, "poison %":25}, ['amulet', 'ring']),
	Item("Solael's Bloodbinding", {"defense":16, "health":150}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item("Solael's Glare", {"cold %":55, "electrocute %":55, "frostburn %":55, "health":250, "lightning %":55, "pierce resist":10}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item("Solael's Soulbinding", {"pierce resist":10, "vitality resist":10}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item("Solael's Vision", {"burn %":55, "electrocute %":55, "fire %":55, "health":250, "lightning %":55, "vitality resist":10}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item("Solael's Voidward", {"chaos resist":15}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item("Solael's Voracity", {"bleed %":55, "health":250, "pierce":12, "pierce %":55}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item('Solar Radiance', {"energy absorb":10, "fire":10, "fire %":35, "offense":22}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item('Solarstorm Powder', {"fire resist":12, "lightning resist":12}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item('Song of the Elements', {"cold %":30, "elemental resist":15, "fire %":30}, ['amulet', 'ring']),
	Item('Soulwarp Powder', {"aether %":36, "burn %":36, "defense":20, "fire %":36}, ['amulet', 'ring']),
	Item('Sparkbloom Powder', {"elemental":10, "elemental %":40, "offense":25, "pet attack speed":3}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item('Spellward Powder', {"aether resist":9, "vitality resist":9}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item('Spikeshell Powder', {"acid %":40, "cold %":40, "frostburn %":40, "offense":25, "pet health %":6, "poison %":40}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item('Spirit of Vengeance', {"health %":4, "retaliation %":16, "vitality %":30, "vitality retaliation":75}, ['amulet', 'ring']),
	Item('Spiritguard Powder', {"vitality resist":12}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item('Stardust', {"cold %":40, "electrocute %":40, "frostburn %":40, "health %":4, "lightning %":40}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item('Steelbloom Powder', {"bleed %":50, "internal %":50, "offense %":2, "physical":12, "physical %":50}, ['amulet', 'ring']),
	Item('Stonetusk Hoof', {"armor":35, "internal %":25, "physical %":25}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item('Storm Powder', {"health":100, "lightning resist":15, "lightning retaliation":54, "retaliation %":10}, ['amulet', 'ring']),
	Item("Stormcaller's Ash", {"aether %":40, "defense":20, "electrocute %":40, "lightning %":40}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item('Stormtail Viper Venom', {"electrocute %":25, "lightning %":25, "offense":20}, ['amulet', 'ring']),
	Item("Survivor's Ally", {"elemental resist":12, "pet all damage %":15, "pet health %":12}, ['amulet', 'ring']),
	Item("Survivor's Ingenuity", {"all damage %":20, "defense %":2, "offense %":2}, ['amulet', 'ring']),
	Item("Survivor's Perseverance", {"aether %":30, "aether resist":12, "chaos %":30, "chaos resist":12}, ['amulet', 'ring']),
	Item("Survivor's Resilience", {"block %":3, "blocked damage %":20, "health %":3}, ['amulet', 'ring']),
	Item("Sylvarria's Essence", {"acid resist":15, "offense %":3, "pet acid resist":30, "pet offense %":4}, ['amulet', 'ring']),
	Item("Traveler's Boon", {"armor":40, "move speed":2, "slow resist":15, "trap resist":10}, ['amulet', 'ring']),
	Item('Troll Wart Powder', {"health %":3, "health/s":16, "health/s %":8}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item('Typhoon Powder', {"defense":70, "electrocute %":50, "health":350, "lightning %":50, "pierce %":50}, ['amulet', 'ring']),
	Item("Ulgrim's Guile", {"cold %":35, "offense":22, "pierce":8, "pierce %":25}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item("Ulo's Lifegiving Waters", {"bleed resist":15, "health %":6, "pet aether %":60, "pet attack speed":8}, ['amulet', 'ring']),
	Item("Uroboruuk's Anguish", {"chaos %":30, "health":200, "reflected damage reduction":10, "vitality %":30}, ['amulet', 'ring']),
	Item("Uroboruuk's Path", {"aether %":30, "energy/s":1.2, "health %":4}, ['amulet', 'ring']),
	Item("Uroboruuk's Word", {"bleed resist":18, "cold %":30, "defense":18, "vitality %":30}, ['amulet', 'ring']),
	Item('Veilworm Powder', {"acid resist":15, "aether %":36}, ['amulet', 'ring']),
	Item('Venomguard Powder', {"acid resist":18}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item("Viloth's Bite", {"poison":[16, 5], "poison %":30, "vitality resist":12}, ['amulet', 'ring']),
	Item('Viper Scale', {"defense":20, "health":200, "pierce %":36}, ['amulet', 'ring']),
	Item('Viper Venom', {"acid %":40, "cold %":40, "frostburn %":40, "poison":[10, 5], "poison %":40}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item('Void Ash', {"acid %":36, "chaos":10, "chaos %":36, "poison %":36}, ['amulet', 'ring']),
	Item('Void Salt', {"burn %":36, "chaos %":36, "defense":20, "fire %":36}, ['amulet', 'ring']),
	Item('Void Tar', {"armor %":5, "chaos %":40, "health %":4}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item('Void Tongue', {"chaos %":36, "stun resist":8, "vitality %":36, "vitality decay %":36}, ['amulet', 'ring']),
	Item('Voidbeast Powder', {"chaos %":25, "offense":18, "vitality %":25}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item('Voidvine Powder', {"chaos resist":6, "fire":8, "fire %":25}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item('Wendigo Bloodscent Powder', {"bleed resist":15}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item('Wendigo Fur', {"health":200, "internal %":40, "physical %":40, "vitality %":40, "vitality decay %":40}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item('Wendigo Lifescent Powder', {"health %":4}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item('Wendigo Soulscent Powder', {"vitality resist":15}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
	Item('Whipvine Powder', {"bleed %":40, "internal %":40, "physical":10, "physical %":40}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item('Wight Skin Powder', {"aether resist":15, "chaos resist":15, "energy/s":1.2}, ['amulet', 'ring']),
	Item("Winter's Chill", {"cold %":30, "freeze resist":15, "frostburn %":30}, ['amulet', 'ring']),
	Item('Winterbloom Powder', {"cold %":25, "frostburn %":25, "offense":18}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item("Witch's Black Flame", {"burn %":50, "chaos %":50, "fire %":50, "health":350, "stun resist":8}, ['amulet', 'ring']),
	Item("Witch's Powder", {"pet attack speed":6, "pet offense %":3}, ['axe', 'dagger', 'mace', 'offhand', 'ranged', 'scepter', 'shield', 'sword']),
	Item('Woolly Bristlehorn Powder', {"defense":20, "offense":25, "reflected damage reduction":15}, ['amulet', 'ring']),
	Item("Wraith's Scream", {"cold %":50, "frostburn %":50, "offense":75, "vitality":12, "vitality %":50, "vitality decay %":50}, ['amulet', 'ring']),
	Item('Wraithtouch Powder', {"cold resist":18}, ['arms', 'chest', 'feet', 'head', 'legs', 'shoulders', 'waist']),
]

equipment = {}
equipment["Beastcaller's Shroud"] = Item("Beastcaller's Shroud", {"Summon Briarthorn":2, "Summon Hellhound":2, "armor":982, "defense":22, "elemental resist":24, "health":280, "pet armor %":15, "pet elemental resist":25, "spirit":20}, 'chest')
equipment['Black Scourge'] = Item('Black Scourge', {"Bonds of Bysmiel":2, "Manipulation":2, "chaos %":92, "health":140, "offense":22, "pet chaos resist":30, "pet offense %":4, "skill recharge":4}, 'scepter')
equipment['Death Omen'] = Item('Death Omen', {"Execution":2, "Harbinger of Souls":2, "attack speed":12, "health":300, "lifesteal %":6, "physical":100, "physical to vitality":15, "vitality":9, "vitality %":55, "vitality decay %":55}, 'mace', Ability('Item Skill', {"chance":1, "duration":5, "recharge":2, "skillClass":'Skill_AttackBuff', "trigger":'hit', "type":'buff'}, {"offense":120, "triggered vitality":135}))
equipment['Empowered Bramblewood Amulet'] = Item('Empowered Bramblewood Amulet', {"Mark of Torment":3, "acid resist":60, "armor %":6, "health":355, "physical retaliation":354, "retaliation %":30, "shaman skills":1}, 'amulet')
equipment["Empowered Stormcaller's Gem"] = Item("Empowered Stormcaller's Gem", {"Storm Totem":2, "Wind Devil":2, "elemental resist":20, "lightning %":44, "lightning retaliation":155.5, "offense":30, "retaliation %":33, "skill recharge":5}, 'amulet', Ability('Lightning Bolt', {"chance":0.1, "recharge":2.5, "skillClass":'Skill_AttackRadiusLightning', "trigger":'attack', "type":'attack'}, {"stun %":50, "triggered electrocute":[397, 2], "triggered lightning":772}))
equipment['Lifegiver Signet'] = Item('Lifegiver Signet', {"Battle Surge":2, "Summon Guardian of Empyrion":2, "bleed resist":25, "constitution %":45, "defense":20, "health":270, "lifesteal %":6, "vitality resist":40}, 'ring', Ability('Lifetaker', {"chance":0.08, "recharge":1.5, "skillClass":'Skill_AttackRadius', "trigger":'attack', "type":'attack'}, {"lifesteal %":15, "triggered vitality":220, "weapon damage %":10}))
equipment["Necrolord's Shroud"] = Item("Necrolord's Shroud", {"Undead Legion":3, "armor":909, "elemental resist":33, "energy/s":6.6, "health":550, "pet elemental resist":35, "pet health %":5, "physical resist":3, "pierce resist":15}, 'chest', Ability('Item Skill', {"chance":1, "skillClass":'Skill_BuffRadiusToggled', "trigger":'toggle', "type":'buff'}, {"health %":10, "vitality %":100, "vitality decay %":140}))
equipment['Pendant of the Royal Crown'] = Item('Pendant of the Royal Crown', {"all damage %":25, "chaos resist":15, "cunning %":3, "elemental resist":30, "offense":62, "spirit %":3}, 'amulet')
equipment['Rhowari Lifecaller'] = Item('Rhowari Lifecaller', {"Summon Briarthorn":2, "Summon Familiar":2, "elemental resist":22, "health":160, "pet all damage %":18, "pet attack speed":5, "pet crit damage":10, "vitality resist":18}, 'amulet')
equipment['Rhowari Void Seal'] = Item('Rhowari Void Seal', {"Bloodfrenzy":2, "Demon Fire":2, "Flames of Ignaffar":2, "acid resist":12, "cast speed":4, "chaos %":32, "elemental resist":18, "offense":45, "vitality %":32, "vitality decay %":32}, 'ring')
equipment['Seal of the Royal Crown'] = Item('Seal of the Royal Crown', {"acid resist":24, "all damage %":25, "defense":30, "energy":340, "offense":30, "stun resist":18, "vitality resist":24}, 'ring')
equipment['The Peerless Eye of Beronath'] = Item('The Peerless Eye of Beronath', {"Untamed Rage":2, "all skills":1, "crit damage":8, "elemental resist":15, "light radius":20, "offense":75}, 'amulet', Ability('Item Skill', {"chance":1, "duration":12, "recharge":6, "skillClass":'Skill_AttackBuffRadius', "trigger":'manual', "type":'buff'}, {"defense":110, "energy":-66}))
equipment["Beastcaller's Regalia (2)"] = Item("Beastcaller's Regalia (2)", {"defense %":5}, ['set'])
equipment["Beastcaller's Regalia (3)"] = Item("Beastcaller's Regalia (3)", {"freeze resist":20, "pet aether resist":30, "pet chaos resist":30, "slow resist":20}, ['set'])
equipment["Beastcaller's Regalia (4)"] = Item("Beastcaller's Regalia (4)", {"Conjure Primal Spirit":3, "Summon Hellhound":3}, ['set'], Ability('Bestial Rage', {"chance":1, "duration":6, "recharge":15, "skillClass":'Skill_BuffSelfDuration', "trigger":'hit', "type":'buff'}, {"pet total speed":20}))
equipment['Royal Exuberance (2)'] = Item('Royal Exuberance (2)', {"cunning %":5, "physique %":5, "spirit %":5}, ['set'])
equipment['Royal Exuberance (3)'] = Item('Royal Exuberance (3)', {"all skills":1}, ['set'])
