self.seedSolutions = [
  Solution([xC, fiend, viper, tsunami, raven, kraken, hawk, eel, lizard, xO, winterBlizzard, behemothGiantsBlood, spear, ultos], self),  # 121979 (53)
  Solution([xC, fiend, viper, tsunami, hawk, kraken, eel, light, lizard, jackal, winterBlizzard, behemothGiantsBlood, spear, ultosHandofUltos], self),  # 121794 (53)
  Solution([xC, fiend, viper, tsunami, wraith, hawk, kraken, eel, light, xP, winterBlizzard, behemothGiantsBlood, spear, ultos], self),  # 121610 (53)
  Solution([xC, fiend, viper, tsunami, wraith, quill, kraken, tempest, hawk, eel, ultosHandofUltos, spear], self),  # 120351 (52)
  Solution([xC, viper, tsunami, wraith, eel, rat, quill, kraken, tempest, hawk, xO, ultosHandofUltos, spear], self),  # 119956 (52)
  Solution([xC, viper, tsunami, wraith, eel, rat, quill, kraken, tempest, hawk, spear, ultosHandofUltos], self),  # 119181 (51)
  Solution([xC, viper, tsunami, wraith, eel, rat, quill, kraken, tempest, light, spear, ultos], self),  # 118077 (52)
  Solution([xE, eye, hawk, xC, fiend, viper, tsunami, kraken, eel, xP, xO, panther, behemothGiantsBlood, spear, ultos], self),  # 117513 (53)
  Solution([xC, viper, tsunami, eel, lizard, rat, eye, kraken, quill, tempest, ultosHandofUltos, spear], self),  # 116615 (52)
  Solution([xC, fiend, viper, tsunami, bull, wraith, panther, raven, kraken, hawk, xO, ultosHandofUltos, spear], self),  # 114425 (52)
  Solution([xA, xC, viper, tsunami, eel, lizard, rat, eye, kraken, light, xO, ultosHandofUltos, crownElementalStorm, spear, behemothGiantsBlood], self),  # 114326 (52)
  Solution([xA, xC, fiend, viper, tsunami, wraith, hawk, kraken, eel, light, xP, xO, crownElementalStorm, spear, ultosHandofUltos], self),  # 113983 (50)
  Solution([xA, xE, raven, hawk, xP, tsunami, kraken, viper, wraith, crown, eel, jackal, spear, ultosHandofUltos], self),  # 113870 (50)
  Solution([xA, xC, fiend, viper, tsunami, wraith, raven, kraken, hawk, eel, xP, crownElementalStorm, spear, ultosHandofUltos], self),  # 113852 (50)
  Solution([xE, quill, hawk, xC, fiend, viper, tsunami, kraken, wraith, eel, xP, crownElementalStorm, spear, ultosHandofUltos], self),  # 113849 (50)
  Solution([xC, fiend, viper, tsunami, bull, wraith, panther, hawk, kraken, light, spear, ultos], self),  # 113651 (51)
  Solution([xC, fiend, viper, tsunami, wraith, hawk, kraken, eel, light, xO, panther, spear, ultos], self),  # 113494 (50)
  Solution([xC, fiend, viper, tsunami, wraith, raven, kraken, hawk, eel, xO, panther, spear, ultosHandofUltos], self),  # 113493 (50)
  Solution([xC, viper, tsunami, wraith, eel, rat, quill, kraken, crown, hawk, xP, spear, ultosHandofUltos], self),  # 113317 (50)
  Solution([xE, raven, hawk, xC, fiend, viper, tsunami, kraken, eel, xP, xO, panther, spear, ultos], self),  # 112762 (49)
  Solution([xA, xC, fiend, viper, tsunami, imp, kraken, wraith, crown, hawk, eel, ultosHandofUltos, spear], self),  # 112561 (52)
  Solution([xC, fiend, viper, tsunami, raven, kraken, hawk, eel, xP, xO, panther, spear, ultos], self),  # 112402 (48)
  Solution([xE, hawk, xC, fiend, viper, tsunami, kraken, imp, wraith, xO, panther, spear, ultos], self),  # 112269 (50)
  Solution([xC, fiend, viper, tsunami, bull, wraith, panther, raven, kraken, rat, ultosHandofUltos, spear], self),  # 111800 (52)
  Solution([xA, xC, viper, tsunami, wraith, eel, rat, raven, kraken, hawk, xP, crownElementalStorm, spear, ultosHandofUltos], self),  # 111600 (49)
  Solution([xE, quill, hawk, xC, viper, tsunami, kraken, wraith, eel, rat, xP, crownElementalStorm, spear, ultosHandofUltos], self),  # 111597 (49)
  Solution([xE, hawk, xC, fiend, viper, tsunami, kraken, imp, eel, xO, panther, spear, ultos], self),  # 111397 (49)
  Solution([xC, fiend, viper, tsunami, bull, wraith, panther, rat, kraken, light, spear, ultosHandofUltos], self),  # 111156 (51)
  Solution([xO, panther, tsunami, imp, hawk, kraken, fiend, viper, eel, rat, spear, ultosHandofUltos], self),  # 110893 (50)
  Solution([xA, xE, quill, hawk, xC, viper, tsunami, kraken, eel, rat, guide, crownElementalStorm, spear, ultosHandofUltos], self),  # 110670 (49)
  Solution([xE, hawk, xC, fiend, viper, tsunami, kraken, imp, wraith, eel, xO, spear, ultos], self),  # 110482 (49)
  Solution([xC, fiend, viper, tsunami, imp, kraken, raven, hawk, eel, xP, xO, spear, ultos], self),  # 110406 (49)
  Solution([xC, fiend, viper, tsunami, scorpion, kraken, hawk, eel, guide, jackal, spear, ultosHandofUltos], self),  # 110387 (49)
  Solution([xO, panther, tsunami, imp, raven, kraken, viper, hawk, eel, ghoul, spear, ultosHandofUltos], self),  # 109828 (50)
  Solution([xA, xC, fiend, viper, tsunami, imp, kraken, quill, crown, eel, xP, spear, ultosHandofUltos], self),  # 109715 (50)
  Solution([xC, fiend, viper, tsunami, imp, kraken, eel, light, xP, xO, panther, spear, ultos], self),  # 109558 (49)
  Solution([xC, fiend, viper, tsunami, scorpion, kraken, hawk, eel, guide, spear, ultos], self),  # 109152 (47)
  Solution([xE, spider, xP, tsunami, kraken, viper, bull, imp, wraith, ghoul, spear, ultosHandofUltos], self),  # 108232 (51)
  Solution([xC, fiend, viper, tsunami, scorpion, kraken, bat, eel, guide, spear, ultos], self),  # 105980 (49)
  Solution([xC, fiend, viper, tsunami, quill, kraken, owl, tempest, crown, hawk, xO, ultosHandofUltos, behemothGiantsBlood], self),  # 98242 (52)
  Solution([xA, owl, xC, viper, tsunami, tempest, spider, kraken, crown, hawk, ghoul, ultosHandofUltos], self),  # 96499 (50)
  Solution([xA, owl, xC, viper, tsunami, tempest, raven, kraken, crown, hawk, ghoul, ultosHandofUltos], self),  # 96468 (49)
  Solution([xA, xC, viper, tsunami, rat, quill, kraken, crown, tempest, hawk, jackal, xO, ultos], self),  # 95140 (49)
  Solution([xA, wolverine, xC, viper, tsunami, tempest, spider, kraken, hawk, ghoul, xO, crownElementalStorm, ultosHandofUltos], self),  # 94994 (50)
  Solution([xA, xE, quill, raven, crown, xC, viper, tsunami, kraken, tempest, ghoul, ultos], self),  # 94533 (48)
  Solution([xA, xC, viper, tsunami, wraith, rat, quill, kraken, tempest, crown, hawk, ultos], self),  # 94492 (49)
  Solution([xC, fiend, viper, wraith, quill, kraken, tempest, hawk, rat, light, torchMeteorShower, ultos], self),  # 94161 (51)
  Solution([xA, xC, viper, tsunami, rat, quill, kraken, crown, tempest, spider, hawk, ultosHandofUltos], self),  # 93890 (49)
  Solution([xA, xE, quill, hawk, crown, xC, fiend, viper, tsunami, kraken, tempest, wraith, ultos], self),  # 93576 (51)
  Solution([xA, xE, quill, hawk, crown, light, xP, tsunami, kraken, tempest, fiend, viper, xO, ultosHandofUltos], self),  # 92571 (50)
  Solution([xC, fiend, viper, quill, wraith, kraken, tempest, spider, rat, ultosHandofUltos, torchMeteorShower], self),  # 91065 (49)
  Solution([xC, viper, wraith, rat, quill, kraken, tempest, raven, hawk, jackal, ultosHandofUltos, torchMeteorShower], self),  # 90718 (49)
  Solution([xE, quill, light, xC, fiend, viper, wraith, kraken, tempest, rat, torchMeteorShower, crownElementalStorm, ultosHandofUltos], self),  # 86969 (51)
]