self.seedSolutions = [
  Solution([xC, fiend, eye, falcon, huntress, chariot, quill, xP, tsunami, behemoth, sage], self),  # 106780 (53)
  Solution([xC, fiend, eye, falcon, huntress, chariot, quill, xP, tsunami, behemoth, sage], self),  # 106780 (53)
  Solution([xC, fiend, eye, falcon, huntress, chariotWaywardSoul, hawk, quill, xP, lizard, behemoth, sage], self),  # 106543 (53)
  Solution([xC, fiend, eye, falcon, huntress, chariotWaywardSoul, viper, lizard, behemoth, kraken, ultosHandofUltos, xO], self),  # 104373 (53)
  Solution([xC, fiend, eye, falcon, huntress, chariotWaywardSoul, viper, lizard, behemoth, kraken, ultos], self),  # 104243 (53)
  Solution([xC, fiend, eye, falcon, huntress, chariotWaywardSoul, viper, tsunami, behemoth, lizard, ultosHandofUltos, xO], self),  # 99469 (53)
  Solution([xC, fiend, eye, falcon, huntress, chariotWaywardSoul, viper, tsunami, behemoth, lizard, ultos], self),  # 99339 (53)
  Solution([xC, fiend, eye, falcon, huntress, chariotWaywardSoul, viper, tsunami, behemoth, kraken, lizard, xO], self),  # 98795 (53)
  Solution([xC, fiend, eye, falcon, huntress, chariotWaywardSoul, ghoul, xO, xE, xP, tsunami, behemoth, kraken], self),  # 96182 (53)
  Solution([xC, fiend, eye, falcon, huntress, chariotWaywardSoul, ghoul, xO, xA, xP, tsunami, behemoth, kraken], self),  # 96182 (53)
  Solution([xC, fiend, eye, falcon, huntress, chariotWaywardSoul, ghoul, viper, lizard, behemoth, kraken, xO], self),  # 96004 (53)
  Solution([xC, fiend, eye, falcon, huntress, chariotWaywardSoul, berserker, xO, xP, tsunami, behemoth, kraken], self),  # 95824 (53)
  Solution([xC, fiend, eye, falcon, huntress, chariotWaywardSoul, berserker, viper, lizard, behemoth, kraken], self),  # 95231 (53)
  Solution([xC, fiend, eye, falcon, huntress, chariotWaywardSoul, crownStorm, fox, xO, xP, wraith, behemoth, sageElementalSeeker], self),  # 94690 (53)
  Solution([xC, fiend, eye, falcon, huntress, chariotWaywardSoul, crownStorm, viper, tsunami, behemoth, kraken, xO], self),  # 94307 (53)
  Solution([xC, fiend, eye, falcon, huntress, chariotWaywardSoul, crownStorm, ghoul, xO, xP, lizard, behemoth, kraken], self),  # 92607 (53)
  Solution([xC, fiend, eye, falcon, huntress, chariotWaywardSoul, crownStorm, berserker, xP, lizard, behemoth, kraken], self),  # 91834 (53)
  Solution([xC, fiend, eye, falcon, huntress, chariotWaywardSoul, crownStorm, berserker, viper, tsunami, behemoth], self),  # 87124 (53)
  Solution([xC, fiend, eye, falcon, huntress, chariotWaywardSoul, crownStorm, berserker, ghoul, xP, lizard, behemoth], self),  # 85423 (53)
  Solution([xC, fiend, eye, falcon, huntress, chariotWaywardSoul, crownStorm, berserker, ghoul, viper, lizard, behemothGiantsBlood], self),  # 78727 (53)
  Solution([xC, fiend, eye, falcon, huntress, chariotWaywardSoul, crownStorm, berserker, ghoul, viper, tsunami, xO], self),  # 71644 (53)
  Solution([xC, fiend, eye, falcon, huntress, chariotWaywardSoul, crownStorm, berserker, ghoul, revenant, lizard, xO], self),  # 69856 (53)
  Solution([xC, fiend, eye, falcon, huntress, chariotWaywardSoul, crownStorm, berserker, ghoul, revenant, viper], self),  # 69694 (53)
]