self.seedSolutions = [
  Solution([xE, quill, hawk, xC, viper, tsunami, kraken, behemoth, wraith, tempest, eel, xO, spear, ultosHandofUltos], self),  # 118905 (55)
  Solution([xP, tsunami, wraith, lizard, toad, tempest, hawk, kraken, viper, behemoth, xC, spear, ultosHandofUltos], self),  # 118207 (54)
  Solution([xE, quill, hawk, xC, viper, tsunami, kraken, behemoth, wraith, tempest, eel, spear, ultosHandofUltos], self),  # 118131 (54)
  Solution([xC, viper, tsunami, wraith, eel, rat, quill, kraken, tempest, hawk, behemothGiantsBlood, spear, ultosHandofUltos], self),  # 116748 (54)
  Solution([xC, viper, tsunami, wraith, eel, rat, quill, kraken, tempest, light, behemothGiantsBlood, spear, ultosHandofUltos], self),  # 115146 (54)
  Solution([xA, falcon, quill, raven, hawk, xC, viper, wraith, kraken, behemoth, tempest, sageElementalSeeker, ultosHandofUltos], self),  # 112933 (54)
  Solution([xE, eye, hawk, xA, crown, xC, viper, tsunami, kraken, behemoth, lizard, eel, spear, ultos], self),  # 111097 (54)
  Solution([xC, fiend, viper, tsunami, raven, kraken, hawk, eel, lizard, xO, winterBlizzard, behemothGiantsBlood, spear, ultos], self),  # 110277 (53)
  Solution([xC, fiend, viper, tsunami, quill, kraken, wraith, tempest, hawk, eel, xO, spear, ultos], self),  # 110214 (54)
  Solution([xC, fiend, viper, tsunami, hawk, kraken, eel, light, lizard, jackal, winterBlizzard, behemothGiantsBlood, spear, ultosHandofUltos], self),  # 110178 (53)
  Solution([xC, viper, tsunami, wraith, eel, rat, quill, kraken, tempest, hawk, xO, spear, ultos], self),  # 109705 (53)
  Solution([xA, falcon, light, crown, xC, viper, tsunami, kraken, behemoth, lizard, eel, spear, ultos], self),  # 109524 (53)
  Solution([xC, fiend, viper, tsunami, quill, kraken, wraith, tempest, hawk, eel, spear, ultos], self),  # 109439 (53)
  Solution([xC, fiend, viper, tsunami, wraith, raven, kraken, hawk, lizard, xO, panther, behemothGiantsBlood, spear, ultos], self),  # 109155 (54)
  Solution([xC, viper, tsunami, wraith, eel, rat, quill, kraken, tempest, hawk, xO, ultosHandofUltos, spear], self),  # 109060 (52)
  Solution([xC, fiend, viper, tsunami, wraith, hawk, kraken, eel, light, xP, winterBlizzard, behemothGiantsBlood, spear, ultos], self),  # 108956 (53)
  Solution([xC, fiend, viper, tsunami, wraith, quill, kraken, tempest, hawk, eel, ultosHandofUltos, spear], self),  # 108794 (52)
  Solution([xE, spider, xA, xO, panther, tsunami, kraken, viper, behemoth, wraith, wretch, crownElementalStorm, spear, ultosHandofUltos], self),  # 108532 (54)
  Solution([xC, fiend, viper, tsunami, imp, kraken, behemoth, hawk, lizard, xO, panther, spear, ultos], self),  # 108361 (54)
  Solution([xC, viper, tsunami, wraith, eel, rat, quill, kraken, tempest, hawk, spear, ultosHandofUltos], self),  # 108286 (51)
  Solution([xE, quill, light, xC, fiend, viper, tsunami, kraken, wraith, tempest, eel, spear, ultos], self),  # 108198 (54)
  Solution([xC, fiend, eye, viper, tsunami, kraken, wraith, tempest, hawk, lizard, xP, spear, ultosHandofUltos], self),  # 108185 (54)
  Solution([xC, viper, tsunami, wraith, eel, rat, quill, kraken, tempest, light, xO, spear, ultos], self),  # 108104 (53)
  Solution([xC, fiend, viper, tsunami, quill, kraken, wraith, tempest, raven, eel, ultosHandofUltos, spear], self),  # 107751 (53)
  Solution([xC, fiend, eye, viper, tsunami, kraken, wraith, tempest, hawk, eel, xO, spear, ultosHandofUltos], self),  # 107553 (54)
  Solution([xC, viper, tsunami, wraith, eel, rat, quill, kraken, tempest, light, spear, ultos], self),  # 107329 (52)
  Solution([xC, viper, tsunami, imp, quill, kraken, toad, tempest, lizard, jackal, xP, ultosHandofUltos, spear], self),  # 107172 (53)
  Solution([xE, hawk, xC, fiend, viper, tsunami, kraken, imp, lizard, xP, xO, panther, spear, behemothGiantsBlood, ultos], self),  # 106675 (53)
  Solution([xC, fiend, viper, tsunami, imp, kraken, wraith, hawk, light, xO, panther, behemothGiantsBlood, spear, ultosHandofUltos], self),  # 106667 (54)
  Solution([xA, falcon, light, xP, tsunami, kraken, fiend, behemoth, viper, lizard, eel, spear, ultosHandofUltos, crownElementalStorm], self),  # 106618 (55)
  Solution([xO, panther, tsunami, imp, hawk, kraken, fiend, viper, rat, lizard, behemothGiantsBlood, spear, ultos], self),  # 106564 (54)
  Solution([xC, viper, tsunami, eel, lizard, rat, eye, kraken, quill, tempest, ultosHandofUltos, spear], self),  # 106364 (52)
  Solution([xA, xC, viper, tsunami, eel, lizard, rat, eye, kraken, light, xO, ultosHandofUltos, crownElementalStorm, spear, behemothGiantsBlood], self),  # 106019 (52)
  Solution([xP, tsunami, imp, quill, kraken, falcon, tempest, viper, lizard, jackal, ultosHandofUltos, spear], self),  # 105699 (53)
  Solution([xE, eye, hawk, xC, fiend, viper, tsunami, kraken, eel, xP, xO, panther, behemothGiantsBlood, spear, ultos], self),  # 105499 (53)
  Solution([xE, raven, xA, xC, fiend, viper, tsunami, kraken, wraith, crown, lizard, xO, panther, spear, ultosHandofUltos], self),  # 104069 (54)
  Solution([xA, xE, raven, hawk, xP, tsunami, kraken, viper, wraith, crown, eel, jackal, spear, ultosHandofUltos], self),  # 101927 (50)
  Solution([xE, eye, bat, viper, imp, kraken, quill, tempest, owl, light, ultosHandofUltos, sage], self),  # 101824 (55)
  Solution([xC, viper, tsunami, wraith, eel, rat, quill, kraken, crown, hawk, xP, spear, ultosHandofUltos], self),  # 101329 (50)
  Solution([xA, xC, viper, tsunami, rat, quill, kraken, crown, tempest, hawk, ghoul, behemothGiantsBlood, ultos], self),  # 100644 (53)
  Solution([xE, quill, hawk, toad, crown, xC, viper, tsunami, kraken, tempest, ghoul, xO, ultosHandofUltos, behemothGiantsBlood], self),  # 100527 (53)
  Solution([xA, xC, fiend, viper, tsunami, wraith, hawk, kraken, eel, light, xP, xO, crownElementalStorm, spear, ultosHandofUltos], self),  # 100257 (50)
  Solution([xA, xC, fiend, viper, tsunami, wraith, raven, kraken, hawk, eel, xP, crownElementalStorm, spear, ultosHandofUltos], self),  # 100040 (50)
  Solution([xE, quill, hawk, xC, fiend, viper, tsunami, kraken, wraith, eel, xP, crownElementalStorm, spear, ultosHandofUltos], self),  # 99974 (50)
  Solution([xA, xC, fiend, viper, tsunami, imp, kraken, wraith, crown, hawk, eel, ultosHandofUltos, spear], self),  # 99911 (52)
  Solution([xA, xC, viper, tsunami, wraith, eel, rat, raven, kraken, hawk, xP, crownElementalStorm, spear, ultosHandofUltos], self),  # 99532 (49)
  Solution([xC, fiend, viper, tsunami, bull, wraith, panther, raven, kraken, hawk, xO, ultosHandofUltos, spear], self),  # 99487 (52)
  Solution([xE, quill, hawk, xC, viper, tsunami, kraken, wraith, eel, rat, xP, crownElementalStorm, spear, ultosHandofUltos], self),  # 99466 (49)
  Solution([xA, xC, viper, tsunami, rat, quill, kraken, crown, tempest, light, ghoul, xO, ultosHandofUltos, behemothGiantsBlood], self),  # 99172 (53)
  Solution([xE, spider, quill, xA, crown, xO, panther, tsunami, kraken, tempest, viper, behemoth, ultos], self),  # 99081 (54)
  Solution([xA, xC, viper, tsunami, rat, quill, kraken, crown, tempest, light, ghoul, behemothGiantsBlood, ultos], self),  # 99043 (53)
  Solution([xC, fiend, viper, tsunami, wraith, hawk, kraken, eel, light, xO, panther, spear, ultos], self),  # 98998 (50)
  Solution([xC, fiend, viper, tsunami, wraith, raven, kraken, hawk, eel, xO, panther, spear, ultosHandofUltos], self),  # 98912 (50)
  Solution([xC, fiend, eye, falcon, viper, raven, lizard, kraken, owl, light, ultos, behemothGiantsBlood, sage], self),  # 98894 (55)
  Solution([xC, fiend, viper, tsunami, bull, wraith, panther, hawk, kraken, light, spear, ultos], self),  # 98799 (51)
  Solution([xA, xE, quill, hawk, xC, viper, tsunami, kraken, eel, rat, guide, crownElementalStorm, spear, ultosHandofUltos], self),  # 98573 (49)
  Solution([xO, panther, tsunami, imp, raven, kraken, viper, hawk, eel, ghoul, spear, ultosHandofUltos], self),  # 98382 (50)
  Solution([xC, viper, tsunami, rat, quill, kraken, toad, tempest, crown, ghoul, behemothGiantsBlood, ultos], self),  # 98205 (53)
  Solution([xE, raven, hawk, xC, fiend, viper, tsunami, kraken, eel, xP, xO, panther, spear, ultos], self),  # 98173 (49)
  Solution([xC, fiend, viper, tsunami, raven, kraken, hawk, eel, xP, xO, panther, spear, ultos], self),  # 97813 (48)
  Solution([xE, eye, hawk, owl, crown, xA, xC, viper, tsunami, kraken, behemoth, tempest, xO, ultos], self),  # 97809 (54)
  Solution([xE, hawk, xC, fiend, viper, tsunami, kraken, imp, wraith, xO, panther, spear, ultos], self),  # 97685 (50)
  Solution([xA, xC, fiend, viper, tsunami, imp, kraken, quill, crown, eel, xP, spear, ultosHandofUltos], self),  # 97058 (50)
  Solution([xC, fiend, viper, tsunami, bull, wraith, panther, raven, kraken, rat, ultosHandofUltos, spear], self),  # 96880 (52)
  Solution([xE, hawk, xC, fiend, viper, tsunami, kraken, imp, eel, xO, panther, spear, ultos], self),  # 96807 (49)
  Solution([xC, fiend, viper, tsunami, bull, wraith, panther, rat, kraken, light, spear, ultosHandofUltos], self),  # 96322 (51)
  Solution([xO, panther, tsunami, imp, hawk, kraken, fiend, viper, eel, rat, spear, ultosHandofUltos], self),  # 96320 (50)
  Solution([xC, fiend, viper, tsunami, quill, kraken, owl, tempest, crown, hawk, xO, ultosHandofUltos, behemothGiantsBlood], self),  # 96144 (52)
  Solution([xE, hawk, xC, fiend, viper, tsunami, kraken, imp, wraith, eel, xO, spear, ultos], self),  # 95891 (49)
  Solution([xC, fiend, viper, tsunami, imp, kraken, raven, hawk, eel, xP, xO, spear, ultos], self),  # 95870 (49)
  Solution([xE, spider, xP, tsunami, kraken, viper, bull, imp, wraith, ghoul, spear, ultosHandofUltos], self),  # 95340 (51)
  Solution([xC, fiend, viper, tsunami, scorpion, kraken, hawk, eel, guide, jackal, spear, ultosHandofUltos], self),  # 95300 (49)
  Solution([xC, fiend, viper, tsunami, imp, kraken, eel, light, xP, xO, panther, spear, ultos], self),  # 95115 (49)
  Solution([xC, fiend, viper, tsunami, scorpion, kraken, hawk, eel, guide, spear, ultos], self),  # 94065 (47)
  Solution([xC, fiend, viper, tsunami, wraith, falcon, kraken, tempest, eel, xO, winterBlizzard, spear, behemothGiantsBlood], self),  # 92595 (53)
  Solution([xA, owl, xC, viper, tsunami, tempest, raven, kraken, crown, hawk, ghoul, ultosHandofUltos], self),  # 92149 (49)
  Solution([xA, owl, xC, viper, tsunami, tempest, spider, kraken, crown, hawk, ghoul, ultosHandofUltos], self),  # 92132 (50)
  Solution([xC, fiend, viper, tsunami, scorpion, kraken, bat, eel, guide, spear, ultos], self),  # 91099 (49)
  Solution([xA, wolverine, xC, viper, tsunami, tempest, spider, kraken, hawk, ghoul, xO, crownElementalStorm, ultosHandofUltos], self),  # 90545 (50)
  Solution([xA, xE, quill, raven, crown, xC, viper, tsunami, kraken, tempest, ghoul, ultos], self),  # 90206 (48)
  Solution([xA, xC, viper, tsunami, rat, quill, kraken, crown, tempest, hawk, jackal, xO, ultos], self),  # 90021 (49)
  Solution([xA, xC, viper, tsunami, wraith, rat, quill, kraken, tempest, crown, hawk, ultos], self),  # 89380 (49)
  Solution([xA, xC, viper, tsunami, rat, quill, kraken, crown, tempest, spider, hawk, ultosHandofUltos], self),  # 88787 (49)
  Solution([xA, xE, quill, hawk, crown, xC, fiend, viper, tsunami, kraken, tempest, wraith, ultos], self),  # 88447 (51)
  Solution([xE, quill, light, xC, fiend, viper, wraith, kraken, tempest, rat, torchMeteorShower, crownElementalStorm, ultosHandofUltos], self),  # 87904 (51)
  Solution([xA, xE, quill, hawk, crown, light, xP, tsunami, kraken, tempest, fiend, viper, xO, ultosHandofUltos], self),  # 87582 (50)
  Solution([xC, fiend, viper, wraith, quill, kraken, tempest, hawk, rat, light, torchMeteorShower, ultos], self),  # 87544 (51)
  Solution([xC, viper, wraith, rat, quill, kraken, tempest, raven, hawk, jackal, ultosHandofUltos, torchMeteorShower], self),  # 87536 (49)
  Solution([xC, fiend, viper, quill, wraith, kraken, tempest, spider, rat, ultosHandofUltos, torchMeteorShower], self),  # 84315 (49)
]