self.seedSolutions = [
  [xA, xE, bat, viper, gallows, wendigo, behemoth, revenant, xP, eel, god, manticore],
  [xA, xE, bat, hawk, viper, manticore, gallows, wendigo, jackal, eel, xP, revenant, god],
  [xE, bat, scorpion, viper, gallows, eel, bonds, jackal, wendigo, revenant, xP, god],
  [xA, xC, fiend, bat, viper, gallows, eel, wendigo, manticore, xE, xP, revenant, god],
  [xA, xE, bat, fiend, viper, gallows, eel, wendigo, manticore, xO, xP, revenant, god],
  [xA, xC, fiend, bat, viper, gallows, eel, wendigo, manticore, xE, revenant, xP, god],
  [xA, xE, bat, fiend, viper, gallows, wendigo, manticore, xO, xP, eel, revenant, god],
  [xA, xC, fiend, bat, viper, gallows, guide, wendigo, manticore, revenant, xP, god],
  [xE, bat, fiend, viper, manticore, bonds, wraith, gallows, eel, wendigo, god],
  [xE, bat, fiend, witchblade, viper, manticore, gallows, wendigo, eel, wraith, god],
  [xP, gallows, eel, xE, imp, bat, jackal, manticore, bonds, wendigo, viper, god],
  [xC, viper, gallows, rat, wendigo, imp, bat, bonds, manticore, eel, god],
  [xC, viper, gallows, imp, eel, bat, wendigo, fiend, witchblade, bonds, god],
  [xO, tortoise, imp, gallows, eel, bat, fiend, wendigo, jackal, god, manticore],
  [xA, shepherd, wolverine, owl, xC, viper, jackal, eel, wendigo, xO, tortoise, panther, xP, god],
  [xO, tortoise, xE, raven, bat, rat, gallows, panther, watcher, viper, wendigo, god],
  [xA, shepherd, xE, bat, fiend, affliction, bonds, xO, tortoise, dryad, panther, wendigo],
  [xA, shepherd, xE, bat, raven, viper, affliction, bonds, xC, xO, tortoise, wendigo, dryad],
  [xE, hawk, xO, tortoise, gallows, panther, bat, fiend, wendigo, viper, watcher, god],
  [xE, hawk, xO, tortoise, gallows, panther, bat, rat, viper, wendigo, revenant, god]
]