self.seedSolutions = [
  Solution([xC, jackal, xO, panther, hound, staff, eel, xE, raven, bonds, behemoth, xP, god], self),  # 16659 (45)
  Solution([xC, jackal, viper, hound, eel, xO, panther, staff, lion, xE, raven, bonds, god], self),  # 16570 (45)
  Solution([xC, jackal, xO, panther, eel, staff, guide, xE, raven, bonds, behemoth, god], self),  # 16491 (45)
  Solution([xC, vulture, xO, panther, hound, staff, eel, lion, xE, raven, bonds, xP, god], self),  # 16261 (44)
  Solution([xC, fiend, raven, jackal, bonds, xO, panther, hound, staff, eel, xA, xP, god], self),  # 16194 (44)
  Solution([xC, fiend, raven, jackal, bonds, xO, panther, hound, staff, eel, xP, god], self),  # 16176 (43)
  Solution([xC, jackal, viper, imp, raven, bonds, hound, xO, panther, staff, xE, god], self),  # 16118 (44)
  Solution([xC, jackal, viper, imp, raven, bonds, hound, xO, panther, staff, xA, god], self),  # 16118 (44)
  Solution([xC, jackal, viper, imp, raven, bonds, hound, xO, panther, staff, god], self),  # 16100 (43)
  Solution([xC, jackal, viper, imp, raven, bonds, eel, xO, panther, staff, god], self),  # 16021 (43)
  Solution([xC, vulture, xO, panther, imp, staff, raven, bonds, hound, eel, god], self),  # 15956 (44)
  Solution([xC, jackal, viper, hound, xO, panther, staff, stag, xE, raven, bonds, god], self),  # 15943 (43)
  Solution([xC, rat, viper, imp, bonds, witchblade, hound, xO, panther, staff, god], self),  # 15637 (45)
  Solution([xC, jackal, xO, panther, lion, xE, eye, shepherd, raven, bonds, wolverine, xA, wolf], self),  # 15584 (44)
  Solution([xC, fiend, jackal, xO, panther, imp, bonds, staff, hound, bull, god], self),  # 15492 (45)
  Solution([xC, jackal, xO, panther, imp, eye, bonds, shepherd, raven, wolverine, xA, wolf], self),  # 15236 (45)
  Solution([xC, jackal, xO, panther, xE, eye, shepherd, raven, bonds, wolverine, throne, wolf], self),  # 15078 (44)
  Solution([xC, jackal, xO, panther, xA, shepherd, wolverine, xE, raven, bonds, eye, xP, wolf], self),  # 15021 (42)
  Solution([xC, jackal, xO, panther, xE, eye, shepherd, raven, bonds, wolverine, hammer, wolf], self),  # 15013 (43)
  Solution([xC, jackal, xO, panther, xE, eye, shepherd, raven, bonds, wolverine, xA, wolf], self),  # 15012 (41)
  Solution([xC, jackal, xO, panther, xA, shepherd, wolverine, toad, raven, bonds, hawk, wolf], self),  # 15008 (42)
  Solution([xC, jackal, xO, panther, xA, shepherd, wolverine, toad, raven, bonds, light, wolf], self),  # 14937 (42)
  Solution([xC, jackal, xE, eye, shepherd, raven, bonds, witchblade, wolverine, xA, wolf], self),  # 14696 (41)
  Solution([xC, jackal, xE, eye, shepherd, raven, bonds, wolverine, huntress, wolf], self),  # 14584 (42)
  Solution([xC, vulture, xE, eye, shepherd, raven, bonds, witchblade, wolverine, xA, wolf], self),  # 14467 (43)
  Solution([xC, jackal, xO, panther, imp, staff, raven, bonds, lion, xA, shepherd, winterBlizzard, behemothGiantsBlood], self),  # 14421 (45)
  Solution([xC, fiend, raven, scorpion, jackal, bonds, xA, shepherd, wolverine, throne, wolf], self),  # 14349 (44)
  Solution([xC, fiend, raven, xO, panther, eel, staff, bonds, lion, xA, shepherd, behemothGiantsBlood, winterBlizzard], self),  # 14234 (45)
  Solution([xC, jackal, viper, xO, panther, staff, lion, xA, shepherd, xE, raven, bonds, winterBlizzard, behemothGiantsBlood], self),  # 14234 (45)
  Solution([xC, fiend, raven, xO, panther, lion, wraith, shepherd, staff, bonds, winterBlizzard, behemothGiantsBlood], self),  # 14119 (45)
  Solution([xC, viper, xO, panther, staff, lion, xA, shepherd, xE, raven, bonds, behemoth, winterBlizzard], self),  # 14106 (45)
  Solution([xC, jackal, xO, panther, imp, staff, raven, bonds, behemoth, lion, xA, shepherd], self),  # 14091 (44)
  Solution([xC, fiend, raven, jackal, bonds, viper, xO, panther, staff, lion, xA, shepherd, behemothGiantsBlood], self),  # 13946 (45)
  Solution([xC, rat, raven, xO, panther, lion, wraith, shepherd, staff, bonds, winterBlizzard, behemothGiantsBlood], self),  # 13923 (44)
  Solution([xC, jackal, xO, panther, imp, staff, raven, bonds, lion, xA, shepherd, behemothGiantsBlood], self),  # 13876 (41)
  Solution([xC, jackal, xO, panther, lion, hound, staff, xA, shepherd, xE, raven, bonds, winterBlizzard], self),  # 13872 (41)
  Solution([xC, fiend, raven, xO, panther, imp, staff, bonds, lion, xA, shepherd, winterBlizzard], self),  # 13829 (44)
  Solution([xC, fiend, raven, xO, panther, imp, staff, bonds, lion, xA, shepherd, behemothGiantsBlood], self),  # 13809 (43)
  Solution([xC, fiend, raven, xO, panther, lion, hound, staff, bonds, xA, shepherd, behemothGiantsBlood], self),  # 13767 (41)
  Solution([xC, jackal, xO, panther, lion, wraith, shepherd, staff, xE, raven, bonds, winterBlizzard], self),  # 13678 (41)
  Solution([xC, xO, panther, imp, raven, lion, bat, staff, bonds, xA, shepherd, wolverine], self),  # 13652 (45)
  Solution([xC, rat, raven, xO, panther, lion, hound, staff, bonds, xA, shepherd, winterBlizzard], self),  # 13591 (41)
  Solution([xC, rat, raven, xO, panther, lion, hound, staff, bonds, xA, shepherd, behemothGiantsBlood], self),  # 13571 (40)
  Solution([xC, jackal, xO, panther, imp, staff, eye, bonds, shepherd, witchblade, raven], self),  # 13557 (44)
  Solution([xC, jackal, xO, panther, imp, staff, raven, bonds, lion, wraith, shepherd], self),  # 13408 (41)
  Solution([xC, fiend, eye, shepherd, raven, xO, panther, imp, staff, bonds, lion], self),  # 13385 (44)
  Solution([xC, rat, raven, eye, shepherd, xO, panther, lion, hound, staff, bonds], self),  # 13198 (41)
  Solution([xC, rat, raven, eye, shepherd, xO, panther, lion, eel, staff, bonds], self),  # 13120 (41)
  Solution([xC, viper, imp, raven, xO, lion, staff, bonds, xA, shepherd, behemothGiantsBlood], self),  # 12777 (38)
  Solution([xC, fiend, raven, eye, shepherd, viper, bonds, xO, panther, staff], self),  # 12659 (40)
  Solution([xC, fiend, raven, jackal, bonds, xO, panther, lion, xA, shepherd, wolverine, rattosh], self),  # 11884 (43)
  Solution([xC, fiend, raven, bat, bonds, witchblade, xO, panther, lion, xA, shepherd, rattosh], self),  # 11667 (45)
  Solution([xC, xO, panther, lion, blade, shepherd, wolverine, xE, raven, eye, spider, wolf], self),  # 11585 (45)
  Solution([xC, fiend, raven, eye, shepherd, wolverine, toad, wolf, leviathanWhirlpool], self),  # 10897 (40)
]