self.seedSolutions = [
  Solution([xA, xO, lion, xC, fiend, viper, hound, quill, phoenix, messenger, behemoth, hawk, torchMeteorShower, ultosHandofUltos, targoShieldWall], self),  # 58044 (57)
  Solution([xA, xO, lion, xC, fiend, viper, raven, hound, phoenix, messenger, behemoth, hawk, torchMeteorShower, ultosHandofUltos, targoShieldWall], self),  # 57868 (57)
  Solution([xA, xO, lion, xC, fiend, viper, hound, light, phoenix, messenger, behemoth, hawk, torchMeteorShower, ultos, targoShieldWall], self),  # 57830 (57)
  Solution([xA, xO, lion, xC, fiend, viper, raven, hound, phoenix, messenger, behemoth, light, torchMeteorShower, ultosHandofUltos, targoShieldWall], self),  # 57656 (57)
  Solution([xA, xO, lion, xC, fiend, viper, raven, light, lizard, phoenix, messenger, behemoth, torchMeteorShower, ultosHandofUltos, targoShieldWall], self),  # 57145 (57)
  Solution([xE, hawk, xO, lion, xC, fiend, viper, hound, phoenix, behemoth, toad, messenger, torchMeteorShower, ultosHandofUltos, targoShieldWall], self),  # 57095 (57)
  Solution([xO, lion, xC, fiend, viper, hound, quill, phoenix, behemoth, toad, messenger, torchMeteorShower, ultosHandofUltos, targoShieldWall], self),  # 56990 (57)
  Solution([xO, lion, xC, fiend, viper, raven, hound, phoenix, behemoth, toad, messenger, torchMeteorShower, ultosHandofUltos, targoShieldWall], self),  # 56814 (57)
  Solution([xE, hawk, xO, lion, xC, viper, wraith, shieldmaiden, messenger, behemoth, phoenix, crown, targo, ultosHandofUltos], self),  # 55767 (57)
  Solution([xE, xO, lion, xP, imp, xC, fiend, behemoth, viper, phoenix, toad, messenger, torchMeteorShower, ultosHandofUltos, targoShieldWall], self),  # 55607 (57)
  Solution([xE, quill, xO, lion, xC, viper, wraith, shieldmaiden, messenger, behemoth, phoenix, ultosHandofUltos, chariotWaywardSoul, targoShieldWall], self),  # 55497 (57)
  Solution([xO, lion, xC, fiend, viper, quill, wraith, phoenix, shieldmaiden, messenger, crown, ultosHandofUltos, behemothGiantsBlood, targoShieldWall], self),  # 55452 (57)
  Solution([xO, panther, wraith, lion, shieldmaiden, messenger, fiend, viper, raven, phoenix, ultosHandofUltos, obeliskStoneForm, targoShieldWall], self),  # 55450 (57)
  Solution([xE, xO, lion, xC, fiend, viper, wraith, shieldmaiden, messenger, behemoth, phoenix, crown, ultosHandofUltos, targoShieldWall], self),  # 55317 (57)
  Solution([xE, xO, lion, xC, viper, imp, shieldmaiden, behemoth, phoenix, owl, messenger, crown, ultosHandofUltos, targoShieldWall], self),  # 54990 (57)
  Solution([xE, raven, xO, lion, xC, fiend, viper, hound, phoenix, shieldmaiden, wolverine, messenger, behemothGiantsBlood, ultosHandofUltos, targoShieldWall], self),  # 54938 (57)
  Solution([xO, dryad, xC, fiend, viper, raven, hound, phoenix, wolverine, messenger, crown, ultosHandofUltos, behemothGiantsBlood, targoShieldWall], self),  # 53228 (57)
  Solution([xO, panther, imp, lion, shieldmaiden, xC, fiend, phoenix, behemoth, wolverine, messenger, ultosHandofUltos, targoShieldWall], self),  # 52758 (57)
]